export const initialState = {
  currentUserId: "u1",
  users: [
    {
      id: "u1",
      name: "민준",
      handle: "@minjun",
      position: "PG",
      region: "마포",
      school: "연희대",
      company: "프리랜서",
      club: "노을농구회",
      trustScore: 94,
      streak: 3,
      avatarColor: "#58d2c0",
      ratings: { integrated: 1378, modes: { "1v1": 1180, "2v2": 1264, "3v3": 1330, "5v5": 1412 } },
    },
    {
      id: "u2",
      name: "서윤",
      handle: "@seoyun",
      position: "SG",
      region: "마포",
      school: "연희대",
      company: "라임랩",
      club: "노을농구회",
      trustScore: 91,
      streak: 1,
      avatarColor: "#f4c74f",
      ratings: { integrated: 1322, modes: { "1v1": 1085, "2v2": 1222, "3v3": 1302, "5v5": 1368 } },
    },
    {
      id: "u3",
      name: "지후",
      handle: "@jihoo",
      position: "SF",
      region: "마포",
      school: "동교고",
      company: "라임랩",
      club: "노을농구회",
      trustScore: 86,
      streak: 0,
      avatarColor: "#ff8a5b",
      ratings: { integrated: 1288, modes: { "1v1": 1160, "2v2": 1190, "3v3": 1276, "5v5": 1312 } },
    },
    {
      id: "u4",
      name: "태오",
      handle: "@taeo",
      position: "PF",
      region: "마포",
      school: "연희대",
      company: "오픈코트",
      club: "노을농구회",
      trustScore: 88,
      streak: 2,
      avatarColor: "#74a8ff",
      ratings: { integrated: 1420, modes: { "1v1": 1240, "2v2": 1320, "3v3": 1398, "5v5": 1456 } },
    },
    {
      id: "u5",
      name: "하린",
      handle: "@harin",
      position: "C",
      region: "마포",
      school: "서강대",
      company: "오픈코트",
      club: "노을농구회",
      trustScore: 90,
      streak: 0,
      avatarColor: "#d98cff",
      ratings: { integrated: 1351, modes: { "1v1": 1010, "2v2": 1250, "3v3": 1322, "5v5": 1402 } },
    },
    {
      id: "u6",
      name: "도윤",
      handle: "@doyun",
      position: "PG",
      region: "성수",
      school: "건대",
      company: "스틸픽",
      club: "브릿지볼",
      trustScore: 83,
      streak: -1,
      avatarColor: "#ff6f61",
      ratings: { integrated: 1295, modes: { "1v1": 1214, "2v2": 1248, "3v3": 1306, "5v5": 1280 } },
    },
    {
      id: "u7",
      name: "나은",
      handle: "@naeun",
      position: "SG",
      region: "성수",
      school: "건대",
      company: "스틸픽",
      club: "브릿지볼",
      trustScore: 87,
      streak: 2,
      avatarColor: "#7bd389",
      ratings: { integrated: 1256, modes: { "1v1": 1110, "2v2": 1188, "3v3": 1228, "5v5": 1300 } },
    },
    {
      id: "u8",
      name: "현우",
      handle: "@hyunwoo",
      position: "SF",
      region: "성수",
      school: "한양대",
      company: "플레이메이트",
      club: "브릿지볼",
      trustScore: 79,
      streak: 0,
      avatarColor: "#f05d5e",
      ratings: { integrated: 1214, modes: { "1v1": 1155, "2v2": 1196, "3v3": 1208, "5v5": 1220 } },
    },
    {
      id: "u9",
      name: "유나",
      handle: "@yuna",
      position: "PF",
      region: "성수",
      school: "한양대",
      company: "플레이메이트",
      club: "브릿지볼",
      trustScore: 85,
      streak: 1,
      avatarColor: "#ffc857",
      ratings: { integrated: 1340, modes: { "1v1": 1190, "2v2": 1288, "3v3": 1344, "5v5": 1360 } },
    },
    {
      id: "u10",
      name: "시온",
      handle: "@sion",
      position: "C",
      region: "성수",
      school: "건대",
      company: "스틸픽",
      club: "브릿지볼",
      trustScore: 82,
      streak: -2,
      avatarColor: "#8ac7db",
      ratings: { integrated: 1272, modes: { "1v1": 1040, "2v2": 1210, "3v3": 1262, "5v5": 1326 } },
    },
  ],
  teams: [
    {
      id: "t1",
      name: "Noeul Kings",
      homeCourt: "한강 노을코트",
      region: "마포",
      mmr: 1395,
      wins: 18,
      losses: 9,
      accent: "#58d2c0",
      members: [
        { userId: "u1", role: "captain" },
        { userId: "u2", role: "regular" },
        { userId: "u3", role: "candidate" },
        { userId: "u4", role: "regular" },
        { userId: "u5", role: "regular" },
      ],
    },
    {
      id: "t2",
      name: "Bridge Ballers",
      homeCourt: "성수 브릿지파크",
      region: "성수",
      mmr: 1318,
      wins: 14,
      losses: 11,
      accent: "#ff6f61",
      members: [
        { userId: "u6", role: "captain" },
        { userId: "u7", role: "regular" },
        { userId: "u8", role: "regular" },
        { userId: "u9", role: "regular" },
        { userId: "u10", role: "mercenary" },
      ],
    },
  ],
  affiliations: [
    { id: "a1", type: "region", name: "마포", score: 1420, wins: 38, losses: 24 },
    { id: "a2", type: "region", name: "성수", score: 1362, wins: 32, losses: 27 },
    { id: "a3", type: "school", name: "연희대", score: 1398, wins: 21, losses: 13 },
    { id: "a4", type: "company", name: "스틸픽", score: 1298, wins: 17, losses: 16 },
    { id: "a5", type: "club", name: "노을농구회", score: 1448, wins: 29, losses: 18 },
  ],
  matches: [
    {
      id: "m1",
      title: "토요 5v5 공식전",
      mode: "5v5",
      court: "한강 노을코트",
      scheduledAt: "오늘 20:30",
      status: "contract",
      official: true,
      preRegistered: true,
      rules: { targetScore: 21, timeLimit: 12, winByTwo: true, ball: "7호 공" },
      memo: "승자팀 다음 경기 우선권. 현금 정산 없음.",
      evidence: [
        { id: "captain", label: "양팀 주장 확인" },
        { id: "photo", label: "스코어보드 사진" },
      ],
      teamA: { name: "Noeul Kings", teamId: "t1", players: ["u1", "u2", "u3", "u4", "u5"], score: 0 },
      teamB: { name: "Bridge Ballers", teamId: "t2", players: ["u6", "u7", "u8", "u9", "u10"], score: 0 },
      approvals: { teamA: [], teamB: [] },
      result: null,
      ratingResult: null,
      createdAt: "2026-05-31T10:00:00.000Z",
    },
    {
      id: "m0",
      title: "성수 3v3 리벤지",
      mode: "3v3",
      court: "성수 브릿지파크",
      scheduledAt: "어제 21:00",
      status: "confirmed",
      official: false,
      preRegistered: true,
      rules: { targetScore: 15, timeLimit: 10, winByTwo: false, ball: "7호 공" },
      memo: "빠른 입력 테스트용 기록",
      evidence: [{ id: "captain", label: "양팀 주장 확인" }],
      teamA: { name: "Noeul Kings", teamId: "t1", players: ["u1", "u2", "u4"], score: 15 },
      teamB: { name: "Bridge Ballers", teamId: "t2", players: ["u6", "u7", "u9"], score: 12 },
      approvals: { teamA: ["u1", "u2"], teamB: ["u6", "u7"] },
      result: { scoreA: 15, scoreB: 12, submittedAt: "2026-05-30T12:20:00.000Z" },
      ratingResult: [
        { playerId: "u1", integratedDelta: 12.2, modeDelta: 15.8, result: "win" },
        { playerId: "u6", integratedDelta: -10.6, modeDelta: -13.9, result: "loss" },
      ],
      createdAt: "2026-05-30T11:10:00.000Z",
      confirmedAt: "2026-05-30T12:25:00.000Z",
    },
  ],
  notifications: [
    { id: "n1", title: "경기계약서 대기", body: "토요 5v5 공식전의 결과 입력을 기다리고 있습니다.", tone: "match" },
    { id: "n2", title: "3연승", body: "민준의 통합 티어가 Platinum에 가까워지고 있어요.", tone: "tier" },
  ],
};
