import {
  ArrowRight,
  Bell,
  BookOpenCheck,
  CheckCircle2,
  ClipboardCheck,
  Clock3,
  FlaskConical,
  Gauge,
  MapPin,
  Play,
  QrCode,
  ShieldCheck,
  Swords,
  Trophy,
  UserRoundCheck,
  Users,
  UsersRound,
} from "lucide-react";

export const GUIDE_CHAPTERS = [
  {
    id: "start",
    navLabel: "시작",
    eyebrow: "01 · START",
    title: "BOXTIER는 농구 기록 웹입니다.",
    lead: "홈에서 할 일을 확인하고, 방을 만들거나 참가해 경기를 진행한 뒤 내 전적·팀·티어를 관리합니다.",
    image: "/assets/guide/start-home.jpg?v=20260729-guide-r3",
    imageAlt: "홈 화면의 매칭 만들기와 경기 기록하기 버튼",
    caption: "홈에서 예정 경기는 매칭으로, 끝난 경기는 기록으로 시작합니다.",
    steps: [
      {
        title: "방을 만들고 초대합니다",
        body: "예정 경기는 매칭방을 만들고 선수·팀·심판을 초대합니다. 끝난 경기는 경기 기록 또는 내 기록으로 남길 수 있습니다.",
        Icon: Swords,
      },
      {
        title: "홈에서 할 일을 확인합니다",
        body: "받은 초대, 출석, 참가 확인, 이의 처리처럼 지금 해야 할 일이 홈 액션 큐에 먼저 표시됩니다. 예정 경기와 최근 실제 출전 기록도 함께 확인합니다.",
        Icon: Bell,
      },
      {
        title: "역할에 맞게 경기와 기록을 끝냅니다",
        body: "심판·방장·경기시계 담당자·선수의 권한은 분리됩니다. 열린 이의를 처리하고 별도 최종 승인을 마친 확정 경기만 공식 전적이 됩니다.",
        Icon: Trophy,
      },
      {
        title: "내 기록과 팀 이력을 나눠 봅니다",
        body: "홈과 나 메뉴는 내가 실제 출전한 개인전·팀전을 보여줍니다. 팀 히스토리는 내가 뛰지 않은 소속팀 경기까지 포함할 수 있습니다.",
        Icon: ClipboardCheck,
      },
    ],
    callout: {
      title: "필수 웹 기능은 평생 무료",
      body: "경기 모집·참가, 기본 경기시계, 기록 입력·확정 기록 열람, 티어 조회 같은 필수 웹 기능은 서비스 운영 기간 동안 이용료를 받지 않습니다.",
      details: [
        "구장비·심판비·기록비·장비비·통신비는 무료 범위에서 제외됩니다.",
        "현재 알파 테스트 중이므로 중요한 경기 전에는 방의 규칙·명단·역할을 다시 확인하세요.",
      ],
      Icon: ShieldCheck,
    },
    actions: [
      { to: "/app/guide/practice", label: "연습 경기 시작", Icon: FlaskConical, primary: true },
      { to: "/app/create?intent=record", label: "경기 기록하기", Icon: ClipboardCheck },
    ],
  },
  {
    id: "matching",
    navLabel: "매칭",
    eyebrow: "02 · MATCHING",
    title: "방을 만들고 사람을 초대합니다.",
    lead: "경기 방식과 정원을 정한 뒤 선수·팀·심판을 초대하고, 수락 상태와 자리를 확인합니다.",
    image: "/assets/guide/matching-create.jpg?v=20260728-guide-r2",
    imageAlt: "방 만들기 기본 설정의 공개 범위와 경기 방식 선택 화면",
    caption: "공개 범위, 경기 목적, 팀 구성, 일정과 인원을 한 화면에서 정합니다.",
    steps: [
      {
        title: "방 설정",
        body: "공개·비공개, 친선·경쟁, 경기 전 구성·현장 픽업, 즉시·예약, 1v1·2v2·3v3·5v5, 출전·후보 정원과 경기력 점수(MMR) 범위를 정합니다.",
        Icon: Users,
      },
      {
        title: "선수·팀 초대",
        body: "경기 구성에 맞게 빈 출전·후보 자리에서 선수 또는 상대 팀을 검색해 초대합니다.",
        Icon: Gauge,
      },
      {
        title: "심판 초대",
        body: "방장은 자격 심판을 초대할 수 있습니다. 공개방은 조건을 충족한 심판이 직접 참여할 수 있고, 비공개방은 초대된 대상만 들어옵니다.",
        Icon: Swords,
      },
      {
        title: "초대 수락과 현장 출석",
        body: "초대받은 사람은 홈 액션 큐 또는 방에서 수락합니다. QR 출석은 경기시계를 사용하는 일반 공개 매칭과 대회 경기에서 사용할 수 있습니다.",
        Icon: Clock3,
      },
    ],
    callout: {
      title: "초대 수락과 현장 출석은 다릅니다",
      body: "현장 픽업은 체크인한 선수만 배치안에 넣습니다. 배정 심판 또는 방장이 A/B와 대기를 최종 확정해야 경기를 시작할 수 있습니다.",
      details: [
        "초대 수락은 출석이 아닙니다. 현장에서 출석한 선수만 경기 명단에 배치합니다.",
        "QR 토큰은 5분마다 바뀌며 경기 20분 전부터 로그인한 사전 등록 선수의 출석만 확인합니다.",
        "시작 후 QR은 경기 전에 등록됐지만 미출석 처리된 선수를 원래 사이드 후보로 등록할 뿐, 출전·팀 배치를 자동 확정하지 않습니다.",
        "픽업방은 모집 중 A/B를 정하지 않습니다. 체크인 뒤 참석자만 직접·랜덤·MMR 균형 방식으로 나누고 배정 확정 후 시작합니다.",
      ],
      Icon: CheckCircle2,
    },
    actions: [
      { to: "/app/create", label: "매칭 만들기", Icon: Swords, primary: true },
      { to: "/app/recruiting", label: "매칭 보기", Icon: ArrowRight },
    ],
  },
  {
    id: "attendance",
    navLabel: "출석",
    eyebrow: "03 · ATTENDANCE",
    title: "QR 출석과 실제 출전은 다릅니다.",
    lead: "초대 수락, 현장 출석, 지각 후보 등록, 실제 교체 출전을 순서대로 확인합니다.",
    image: "/assets/guide/attendance-qr.png?v=20260728-attendance-r1",
    imageAlt: "QR 출석 코드와 A/B 사이드별 출석 상태가 함께 표시된 출석판",
    caption: "방장·배정 심판은 출석판을 확인하고, 선수는 현장에서 QR을 스캔합니다.",
    steps: [
      {
        title: "QR 적용 경기 확인",
        body: "QR 출석은 경기시계를 사용하는 일반 공개 매칭과 대회 경기에서 사용합니다. 공개 경쟁전과 대회는 기본 사용하고, 공개 친선전은 방을 만들 때 선택합니다. 대회 출석판은 배정 심판이 운영합니다.",
        Icon: ShieldCheck,
      },
      {
        title: "경기 전 QR 출석",
        body: "경기 20분 전부터 경기시계 담당자 화면의 QR을 로그인한 사전 등록 선수가 스캔합니다. 출전·후보 선수가 모두 출석하면 예정시간 전에도 시작할 수 있고, QR은 경기와 5분 구간에 묶인 서버 서명값입니다.",
        Icon: QrCode,
      },
      {
        title: "미출석과 지각 QR",
        body: "경기 시작 시 미출석 선수를 확정합니다. 진행 중에는 그 선수만 지각 QR로 원래 사이드 후보에 등록할 수 있으며 새 선수를 추가하지 않습니다.",
        Icon: Clock3,
      },
      {
        title: "실제 교체 출전",
        body: "지각 QR은 후보 등록까지만 처리합니다. 후보 본인의 자진 교체 또는 배정 심판의 교체가 실제로 기록돼야 출전시간·개인 전적·MMR 출전자로 계산합니다.",
        Icon: UserRoundCheck,
      },
    ],
    callout: {
      title: "출석판은 서버 상태로 자동 갱신합니다",
      body: "체크인 참가자 표는 3초, 경기 전 QR 패널은 15초, 경기시계와 지각 QR은 3초 간격으로 서버 상태를 다시 확인합니다. 수동 새로고침도 같은 서버 원본을 읽습니다.",
      details: [
        "초대 수락만으로 현장 출석이 되지 않고, 경기 전 QR 출석만으로 출전·후보 자리를 바꾸지 않습니다.",
        "만료된 QR, 다른 경기의 QR, 서명이 잘못된 QR, 미등록 사용자 스캔은 거부합니다.",
        "경기 시작 때 미출석 처리된 사전 등록 선수만 지각 QR을 사용할 수 있습니다.",
        "지각 QR 뒤 실제 교체하지 않으면 팀 히스토리에는 경기 자체가 보여도 홈·나 메뉴의 개인 출전 기록에는 포함되지 않습니다.",
      ],
      Icon: CheckCircle2,
    },
    actions: [
      { to: "/app/matches", label: "내 일정 확인", Icon: QrCode, primary: true },
      { to: "/app/guide?chapter=live", label: "경기 진행 보기", Icon: ArrowRight },
    ],
  },
  {
    id: "live",
    navLabel: "진행",
    eyebrow: "04 · 경기 진행",
    title: "심판·경기시계 담당자·선수가 역할을 나눕니다.",
    lead: "심판 유무와 경기시계 사용 여부에 따라 점수·기록·최종 승인 권한이 분리됩니다.",
    image: "/assets/guide/live-clock.jpg?v=20260728-guide-r3",
    imageAlt: "A/B 점수판과 30초 샷클락이 함께 열린 가로형 BOXTIER 경기시계",
    caption: "지정된 담당자 화면에서 A/B 점수와 경기시간을 조작하고 샷클락을 초기화합니다.",
    steps: [
      {
        title: "심판이 있는 경기",
        body: "배정 심판이 출석, 경기 시작, 양쪽 기록, 경기 종료와 결과 제출을 맡습니다.",
        Icon: Play,
      },
      {
        title: "심판이 없는 경기",
        body: "방장이 출석·시작·종료·최종 승인을 맡습니다. 시계를 쓰면 담당자가 양쪽 점수와 시계·샷클락·QR을 맡고, 시계를 쓰지 않으면 방장이 양쪽 점수를 맡습니다.",
        Icon: UserRoundCheck,
      },
      {
        title: "후보 교체",
        body: "후보는 같은 사이드 출전 선수와 본인 교체할 수 있습니다. 배정 심판도 양쪽 교체를 처리할 수 있지만 무심판 방장·파티장·다른 선수는 타인을 교체할 수 없습니다.",
        Icon: Clock3,
      },
      {
        title: "경기시계",
        body: "출전 선수·후보·심판 중 지정된 담당자가 경기시계·샷클락과 출석 QR을 맡습니다. 양쪽 점수는 심판 경기에서는 배정 심판, 무심판 경기에서는 시계 담당자가 조작합니다. 담당 기기에 연결된 워치·비오디오 미디어 리모컨으로도 샷클락을 초기화할 수 있습니다.",
        Icon: Gauge,
      },
    ],
    callout: {
      title: "정상 사용 여부는 서버 기록으로 판단합니다",
      body: "경기 시작 처리 후 5분 안에 시계를 시작하고, 정규 예상시간의 70% 이상 실제 진행한 뒤 시계 종료를 남겨야 정상 사용 후보가 됩니다.",
      details: [
        "샷클락은 사용 안 함·24초·30초·60초 중 고르는 선택 기능이며 MMR 검증 기준은 경기시계입니다.",
        "휴대폰·태블릿의 블루투스 설정에서 워치 또는 비오디오 미디어 리모컨을 먼저 연결합니다. 현재 경기시계 담당자가 라이브 시계 화면을 한 번 터치한 뒤 리모컨의 재생 또는 일시정지를 누르면 설정한 샷클락 시간으로 초기화됩니다.",
        "별도 연결 버튼이나 기기 목록은 없습니다. 휴식·종료·읽기 전용 화면에서는 동작하지 않으며, 이어폰·헤드셋은 부저 소리를 가져갈 수 있어 지원 기기로 안내하지 않습니다.",
        "담당자는 출전 선수·후보·배정 심판 중 현장에서 정하고 넘길 수 있습니다. 넘긴 뒤 이전 담당자 화면은 읽기 전용이 됩니다.",
        "지각 QR만 찍고 후보에서 실제 교체하지 않은 선수는 개인 전적과 MMR 출전자로 계산하지 않습니다.",
        "구간 시간이 0이어도 바로 끝내지 않아 연장할 수 있습니다. 실제 시계 시작 90분 뒤에는 사후 기록 단계로 전환됩니다.",
        "전체화면·화면 유지·부저는 기기별 베타이며 브라우저 제한이 적용될 수 있습니다.",
      ],
      Icon: ShieldCheck,
    },
    actions: [
      { to: "/app/recorder", label: "플레이 보기", Icon: Play, primary: true },
      { to: "/app/create", label: "방 만들기", Icon: ArrowRight },
    ],
  },
  {
    id: "records",
    navLabel: "기록",
    eyebrow: "05 · RECORDS",
    title: "기록 유형과 확인 절차를 구분합니다.",
    lead: "현장에서 진행한 일반 경기, 경기 후 함께 확인하는 기록, 내가 직접 쓴 기록은 권한·확정·MMR 규칙이 서로 다릅니다.",
    image: "/assets/guide/records-create.jpg?v=20260728-guide-r2",
    imageAlt: "경기 기록과 내 기록을 선택하는 기록 만들기 화면",
    caption: "함께한 경기 기록과 개인용 내 기록을 목적에 맞게 나눠 시작합니다.",
    steps: [
      {
        title: "현장 일반 경기",
        body: "심판 경기는 심판이 점수·개인 스탯·이의·최종 승인을 맡습니다. 무심판 경기는 팀 점수만 저장하고 방장이 이의와 최종 승인을 맡습니다.",
        Icon: ClipboardCheck,
      },
      {
        title: "사후 경기기록",
        body: "함께한 경기를 나중에 만들며 개인 스탯은 생성하지 않습니다. 실제 참가자 2/3 이상이 24시간 안에 내 참가 확인을 해야 확정 조건을 충족합니다.",
        Icon: Users,
      },
      {
        title: "내 기록",
        body: "작성자가 자기 점수와 개인 스탯을 저장합니다. 공개·비공개를 고를 수 있지만 공식 전적·업적·MMR과는 별도로 집계됩니다.",
        Icon: ShieldCheck,
      },
      {
        title: "내 기록 메뉴",
        body: "통합은 실제 출전한 개인전과 팀전의 합계입니다. 개인전·팀전·내 기록 필터로 통계, 날짜별 기록, 최근 6개월과 장기 보관 기록을 같은 기준으로 나눕니다.",
        Icon: CheckCircle2,
      },
    ],
    callout: {
      title: "경기 기록과 내 기록",
      body: "경기 기록은 함께한 참가자 확인을 거치는 사후 공동 기록입니다. 내 기록은 승인 없이 빠르게 남기는 개인용 기록입니다.",
      details: [
        "사후 경기 기록은 확인 기간 안에 참가를 확인한 선수만 서버 정책에 따라 개인 MMR 반영 대상이 되며 팀 MMR은 반영하지 않습니다. 내 기록은 MMR에 반영되지 않습니다.",
        "사후 경기 기록은 참가자 2/3 이상이 내 참가 확인을 해야 하며, 24시간 뒤 기준 충족과 열린 신고 없음이 확인되면 자동 확정됩니다.",
        "실제 시간이 겹치는 다른 공식 경기가 있으면 현장 경기 시작·결과 확정·MMR 반영 또는 사후 기록 확정을 막습니다.",
        "최종 승인 뒤에는 새 이의신청을 받지 않습니다. 이후 문제는 경기 신고로 접수합니다.",
        "일반 경쟁전은 별도 방 흐름에서 결과 확정 조건을 충족해야 MMR 반영 대상이 됩니다.",
      ],
      Icon: BookOpenCheck,
    },
    actions: [
      { to: "/app/create?intent=record", label: "경기 기록", Icon: ClipboardCheck, primary: true },
      { to: "/app/recorder", label: "기록 보기", Icon: ArrowRight },
    ],
  },
  {
    id: "tier",
    navLabel: "티어",
    eyebrow: "06 · TIER",
    title: "티어는 확정 기록에서 자동 계산됩니다.",
    lead: "MMR은 실력이 비슷한 상대를 찾고 순위를 계산하는 경기력 점수입니다. 조건을 충족한 경쟁전 결과가 경기 방식별 MMR과 통합 MMR에 쌓입니다.",
    image: "/assets/guide/tier-profile.jpg?v=20260728-guide-r2",
    imageAlt: "프로필의 통합 MMR과 모드별 MMR 카드",
    caption: "프로필에서 통합 티어와 1v1·2v2·3v3·5v5 모드별 MMR을 확인합니다.",
    steps: [
      {
        title: "자동 계산",
        body: "저장된 MMR에서 티어가 계산됩니다. 첫 확정 경쟁전 5경기 동안은 배정 전으로 표시하고, 배치가 끝나면 브론즈부터 다이아몬드 사이의 티어를 표시합니다. 상세 산식은 공개하지 않습니다.",
        Icon: Trophy,
      },
      {
        title: "반영 대상",
        body: "확정된 경쟁전만 기본 대상입니다. 현장 픽업도 경쟁전과 검증 조건을 선택하면 반영되며, 친선전·사후 경기 기록·내 기록은 기록만 남습니다.",
        Icon: CheckCircle2,
      },
      {
        title: "시계 검증",
        body: "5분 안 시작, 명시적 시계 종료, 예상 정규시간의 70% 이상 실제 진행을 모두 확인합니다.",
        Icon: Clock3,
      },
      {
        title: "개인·팀 MMR",
        body: "개인은 통합과 1v1·2v2·3v3·5v5 MMR을 나눠 봅니다. 팀 MMR도 확정 경기와 확인된 실제 참여 명단을 서버에서 검증해 계산합니다. 상세 산식과 내부 보정값은 공개하지 않습니다.",
        Icon: Gauge,
      },
    ],
    callout: {
      title: "경기시계 사용만으로 MMR 반영이 확정되지는 않습니다",
      body: "정상 사용은 경기 검증 조건 중 하나입니다. 최종 반영 여부와 결과는 전체 경기 검증을 거쳐 서버에서 결정합니다.",
      details: [
        "경기시계 도입 전에 시작된 경기에는 시계 감산을 소급 적용하지 않습니다.",
        "통합 MMR과 모드별 MMR은 프로필에서 따로 확인할 수 있습니다.",
        "랭크보드는 내 지역 개인·팀 순위와 전국 순위를 나누고, 시즌 허브는 개인 승격권·팀 승격권·라이벌 매치업을 보여줍니다.",
      ],
      Icon: ShieldCheck,
    },
    actions: [
      { to: "/app/profile", label: "내 티어 보기", Icon: Trophy, primary: true },
      { to: "/app/rankings", label: "랭킹 보기", Icon: ArrowRight },
    ],
  },
  {
    id: "teams",
    navLabel: "팀",
    eyebrow: "07 · TEAMS",
    title: "팀 소속과 경기 역할은 구분됩니다.",
    lead: "팀장은 팀 자체를 관리하고, 실제 경기에서는 방장과 사이드장이 방의 명단과 진행 역할을 맡습니다.",
    image: "/assets/guide/teams.jpg?v=20260728-guide-r2",
    imageAlt: "대표팀 정보와 내 팀 관리 영역이 보이는 팀 메뉴",
    caption: "대표팀과 내 팀을 먼저 확인하고 주변·라이벌·소속 팀을 필요한 만큼 찾아봅니다.",
    steps: [
      {
        title: "내 팀과 대표팀",
        body: "여러 팀에 소속될 수 있고 대표팀을 따로 정할 수 있습니다. 팀장은 가입·역할·팀 정보·엠블럼·홈코트를 관리합니다.",
        Icon: UsersRound,
      },
      {
        title: "팀전 만들기",
        body: "팀전은 팀장만 만드는 기능이 아닙니다. 일반 팀원도 소속팀을 선택해 방을 만들 수 있고, 경기에서는 각 사이드장이 출전·후보 명단을 운영합니다.",
        Icon: Swords,
      },
      {
        title: "팀 찾기",
        body: "내 팀을 먼저 보여주고 주변 팀, 비슷한 연령대·MMR의 라이벌 팀, 같은 소속 팀을 각각 최대 5개 추천합니다. 전체 팀은 검색할 때만 조회합니다.",
        Icon: Gauge,
      },
      {
        title: "팀 전적과 개인 전적",
        body: "팀 히스토리는 팀이 출전한 경기를 기준으로 합니다. 내가 후보로만 남았거나 뛰지 않은 경기는 팀 이력에는 보여도 홈·나 메뉴 개인 전적에는 포함되지 않습니다.",
        Icon: Trophy,
      },
    ],
    callout: {
      title: "팀 파티와 개인 픽업을 섞지 않습니다",
      body: "사전 구성 팀전은 선택한 팀의 한 묶음으로 참가합니다. 픽업방은 모든 참가자를 개인으로 받고 체크인 뒤 A/B를 정합니다.",
      details: [
        "팀전 엔트리는 경기방에서 파티 나가기로 분리하지 않습니다.",
        "팀 MMR은 실제 참여 명단을 서버에서 검증한 뒤 반영합니다.",
        "용병 참가가 포함된 경기의 팀 MMR도 서버 정책에 따라 판정합니다.",
      ],
      Icon: ShieldCheck,
    },
    actions: [
      { to: "/app/teams", label: "내 팀 보기", Icon: UsersRound, primary: true },
      { to: "/app/create", label: "팀전 만들기", Icon: ArrowRight },
    ],
  },
  {
    id: "courts",
    navLabel: "구장",
    eyebrow: "08 · COURTS",
    title: "승인 구장을 찾고 현장 정보를 보완합니다.",
    lead: "구장 프로필에서 위치·시설·리뷰를 확인하고, 새 구장이나 잘못된 정보를 구조화해 제보할 수 있습니다.",
    image: "/assets/guide/courts.jpg?v=20260728-guide-r2",
    imageAlt: "주소 검색과 시설 정보를 입력하는 구장 신청 화면",
    caption: "근처 주소를 먼저 확인하고 시설명·코트 형태·세부 위치를 입력해 구장을 신청합니다.",
    steps: [
      {
        title: "구장 검색과 즐겨찾기",
        body: "팀 홈코트와 경기 구장은 같은 승인 구장 검색기를 사용합니다. 관심 구장은 즐겨찾기에 넣어 홈과 설정에서 빠르게 확인합니다.",
        Icon: MapPin,
      },
      {
        title: "구장 프로필",
        body: "공식 주소·지도 위치, 코트 형태, 바닥, 조명, 유료 여부와 경기 참가자 리뷰를 확인합니다. 저장 좌표가 있으면 지도는 그 위치를 우선합니다.",
        Icon: Gauge,
      },
      {
        title: "새 구장 신청",
        body: "주소를 검색한 뒤 실제 시설명과 세부 위치·시설 정보를 입력합니다. 주변 승인·대기 구장을 먼저 비교해 중복 신청을 줄입니다.",
        Icon: ClipboardCheck,
      },
      {
        title: "수정·중복 신고",
        body: "승인 구장의 위치 오류·운영 상태·중복·기타 문제를 구장 프로필이나 설정에서 신고합니다. 같은 미처리 대상의 중복 신고는 기존 접수로 연결됩니다.",
        Icon: ShieldCheck,
      },
    ],
    callout: {
      title: "구장 정보와 경기 예약은 다릅니다",
      body: "서비스의 승인 구장 정보는 시설 탐색용입니다. 실제 사용 가능 시간, 예약, 비용과 현장 규칙은 방 메모와 시설 운영자 안내를 다시 확인해야 합니다.",
      details: [
        "유료 구장은 방 생성 시 비용 근거와 정산 방식을 명확히 입력합니다.",
        "위험하거나 폐쇄된 시설은 리뷰보다 구장 상태 신고를 먼저 사용합니다.",
        "관리자는 실제 중복 구장 두 개를 모두 유효하게 두지 않고 하나를 정정·무효 처리합니다.",
      ],
      Icon: ShieldCheck,
    },
    actions: [
      { to: "/app/settings/courts", label: "구장 신청", Icon: MapPin, primary: true },
      { to: "/app/settings/favorites", label: "즐겨찾기 보기", Icon: ArrowRight },
    ],
  },
];
