import { DEFAULT_RATING } from "../../lib/constants.js";
import { createProfileShell } from "../../data/repository.js";
import { getMatchEntityMap } from "../../lib/matchUtils.js";
import { hasModeRating, isPlacementComplete } from "../../lib/rating.js";
import { postServerAction } from "../../lib/serverActions.js";
import { isSupabaseConfigured } from "../../lib/supabase.js";
import { useEffect, useMemo } from "react";
import { sortByRating } from "./serverOperations.js";
import { createAppActions } from "./actions.js";
import { useAppDataAdmin } from "./orchestrator/admin.js";
import { APP_DATA_ORCHESTRATOR_DEPENDENCIES } from "./orchestrator/dependencySet.js";
import { useAppDataLoaders } from "./orchestrator/loaders.js";
import { useAppDataRuntime } from "./orchestrator/runtime.js";
import { useAppDataServerActions } from "./orchestrator/serverActions.js";

export function useAppData(authUser = null, appLocation = null) {
  const {
    adminCacheRef,
    adminContext,
    adminContextLoadedAuthRef,
    adminContextPromiseRef,
    adminContextRef,
    adminPromiseRef,
    adminState,
    adminStatus,
    adminStatusRef,
    authEmail,
    authGenerationRef,
    authUserId,
    blockedSettingsCommittedIdsRef,
    blockedSettingsPendingCountRef,
    blockedSettingsSyncRef,
    currentUserId,
    directoryCacheRef,
    directoryPromiseRef,
    directoryStatus,
    directoryStatusRef,
    latestAdminRequestRef,
    latestDirectoryRequestRef,
    latestRecruitingLoadMoreRequestRef,
    latestRecruitingRegionRequestRef,
    matchDetailPromiseRef,
    matchLists,
    matchPagePromiseRef,
    matchPagination,
    matchRecruitingSchedulePromiseRef,
    matchTeamSchedulePromiseRef,
    pendingMatchIdsRef,
    pendingMatchMutationCountsRef,
    pendingRecruitingPostIdsRef,
    playMatchesPromiseRef,
    profileBindings,
    profileKey,
    profileLocked,
    profileRecordArchive,
    profileRecordArchiveRef,
    profileRecordsLoaded,
    profileRecordsPromiseRef,
    profileRefreshPromiseRef,
    publicProfileRecordArchives,
    publicProfileRecordArchivesRef,
    publicProfileRecordsPromiseRef,
    recentMatchMutationTimesRef,
    recentRecruitingMutationTimesRef,
    recruitingPagePromiseRef,
    recruitingPagination,
    recruitingPostPromiseRef,
    recruitingRegionPromiseRef,
    remoteReady,
    remoteReadyRef,
    reportableMatchesPromiseRef,
    serverActionPendingCount,
    serverProfileBound,
    setAdminContext,
    setAdminState,
    setAdminStatus,
    setDirectoryStatus,
    setMatchLists,
    setMatchPagination,
    setProfileBindings,
    setProfileRecordArchive,
    setProfileRecordsLoaded,
    setPublicProfileRecordArchives,
    setRecruitingPagination,
    setServerActionPendingCount,
    setState,
    setTeamRecordArchives,
    settingsAuthUserIdRef,
    settingsSyncQueueRef,
    state,
    stateRef,
    syncedDiscordDeliveryIdsRef,
    teamRecordArchives,
    teamRecordArchivesRef,
    teamRecordsPromiseRef,
    themeCommittedValueRef,
    themeMutationVersionRef,
  } = useAppDataRuntime({
    ...APP_DATA_ORCHESTRATOR_DEPENDENCIES,
    appLocation,
    authUser,
  });

  const {
    loadAdminContext,
    loadAdminSection,
    refreshAdminState,
    trackedPostServerAction,
  } = useAppDataAdmin({
    ...APP_DATA_ORCHESTRATOR_DEPENDENCIES,
    adminCacheRef,
    adminContextLoadedAuthRef,
    adminContextPromiseRef,
    adminContextRef,
    adminPromiseRef,
    adminStatusRef,
    authEmail,
    authGenerationRef,
    authUserId,
    currentUserId,
    latestAdminRequestRef,
    profileBindings,
    profileKey,
    profileLocked,
    setAdminContext,
    setAdminState,
    setAdminStatus,
    setProfileBindings,
    setServerActionPendingCount,
    setState,
  });

  const {
    applyFavoriteToggle,
    currentUser,
    deleteTeamServer,
    ensureRemoteReady,
    ensureServerActionAvailable,
    loadNotifications,
    markNotificationReadServer,
    persistProfileServer,
    refreshCurrentProfile,
    runServerAction,
    submitReportServer,
    syncMatchServer,
    syncRecruitingPostServer,
    syncRefereeServer,
    syncSettingsServer,
    syncTeamInvitationServer,
    syncTeamServer,
    syncTournamentServer,
  } = useAppDataServerActions({
    ...APP_DATA_ORCHESTRATOR_DEPENDENCIES,
    authEmail,
    authGenerationRef,
    authUserId,
    currentUserId,
    pendingMatchIdsRef,
    pendingMatchMutationCountsRef,
    pendingRecruitingPostIdsRef,
    profileLocked,
    profileRefreshPromiseRef,
    recentMatchMutationTimesRef,
    recentRecruitingMutationTimesRef,
    remoteReadyRef,
    setMatchLists,
    setState,
    settingsAuthUserIdRef,
    settingsSyncQueueRef,
    state,
    stateRef,
    trackedPostServerAction,
  });

  const {
    loadCourtDetail,
    loadDirectory,
    loadMatchDetail,
    loadMatchRecruitingSchedule,
    loadMatchTeamSchedule,
    loadMoreMatches,
    loadMoreRecruiting,
    loadPlayMatches,
    loadProfileRecords,
    loadPublicProfileRecords,
    loadRecruitingPost,
    loadRecruitingRegion,
    loadReportableMatches,
    loadTeamRecords,
    submitCourtDetailReview,
  } = useAppDataLoaders({
    ...APP_DATA_ORCHESTRATOR_DEPENDENCIES,
    authEmail,
    authGenerationRef,
    authUserId,
    currentUserId,
    directoryCacheRef,
    directoryPromiseRef,
    latestDirectoryRequestRef,
    latestRecruitingLoadMoreRequestRef,
    latestRecruitingRegionRequestRef,
    matchDetailPromiseRef,
    matchPagePromiseRef,
    matchPagination,
    matchRecruitingSchedulePromiseRef,
    matchTeamSchedulePromiseRef,
    pendingMatchIdsRef,
    pendingRecruitingPostIdsRef,
    playMatchesPromiseRef,
    profileRecordArchiveRef,
    profileRecordsLoaded,
    profileRecordsPromiseRef,
    publicProfileRecordArchivesRef,
    publicProfileRecordsPromiseRef,
    recentMatchMutationTimesRef,
    recentRecruitingMutationTimesRef,
    recruitingPagePromiseRef,
    recruitingPagination,
    recruitingPostPromiseRef,
    recruitingRegionPromiseRef,
    reportableMatchesPromiseRef,
    runServerAction,
    setDirectoryStatus,
    setMatchLists,
    setMatchPagination,
    setProfileRecordArchive,
    setProfileRecordsLoaded,
    setPublicProfileRecordArchives,
    setRecruitingPagination,
    setState,
    setTeamRecordArchives,
    state,
    teamRecordArchivesRef,
    teamRecordsPromiseRef,
    trackedPostServerAction,
  });

useEffect(() => {
    if (!isSupabaseConfigured || !remoteReadyRef.current || !currentUserId) return;
    const deliveries = (state.discordNotificationDeliveries ?? [])
      .filter((delivery) => delivery?.id && delivery.status === "queued")
      .filter((delivery) => delivery.targetUserId === currentUserId)
      .filter((delivery) => !syncedDiscordDeliveryIdsRef.current.has(delivery.id));
    if (!deliveries.length) return;

    deliveries.forEach((delivery) => syncedDiscordDeliveryIdsRef.current.add(delivery.id));
    postServerAction("/api/discord/sync-deliveries", { deliveries }, { allowWhenDisabled: true }).catch((error) => {
      deliveries.forEach((delivery) => syncedDiscordDeliveryIdsRef.current.delete(delivery.id));
      console.warn("Discord delivery sync failed.", error.message);
    });
  }, [currentUserId, state.discordNotificationDeliveries]);

  const rankings = useMemo(
    () => ({
      players: sortByRating(state.users.filter((user) => isPlacementComplete(user.ratings)), (user) => user.ratings?.integrated ?? DEFAULT_RATING),
      mode: (mode) => sortByRating(
        state.users.filter((user) => isPlacementComplete(user.ratings) && hasModeRating(user.ratings, mode)),
        (user) => user.ratings?.modes?.[mode] ?? DEFAULT_RATING,
      ),
      teams: sortByRating(state.teams, (team) => team.mmr),
      affiliations: sortByRating(state.affiliations.filter((affiliation) => affiliation.type !== "club"), (affiliation) => affiliation.score),
    }),
    [state.affiliations, state.teams, state.users],
  );

  const actions = useMemo(
    () => createAppActions({
      adminStatusRef,
      applyFavoriteToggle,
      authEmail,
      authUserId,
      blockedSettingsCommittedIdsRef,
      blockedSettingsPendingCountRef,
      blockedSettingsSyncRef,
      currentUserId,
      deleteTeamServer,
      directoryStatusRef,
      ensureRemoteReady,
      ensureServerActionAvailable,
      loadAdminContext,
      loadAdminSection,
      loadCourtDetail,
      loadDirectory,
      loadMatchDetail,
      loadMatchRecruitingSchedule,
      loadMatchTeamSchedule,
      loadMoreMatches,
      loadMoreRecruiting,
      loadNotifications,
      loadPlayMatches,
      loadProfileRecords,
      loadPublicProfileRecords,
      loadRecruitingPost,
      loadRecruitingRegion,
      loadReportableMatches,
      loadTeamRecords,
      markNotificationReadServer,
      persistProfileServer,
      profileKey,
      profileLocked,
      profileRecordArchiveRef,
      profileRecordsLoaded,
      publicProfileRecordArchivesRef,
      publicProfileRecordsPromiseRef,
      refreshAdminState,
      refreshCurrentProfile,
      runServerAction,
      serverProfileBound,
      setAdminState,
      setMatchLists,
      setProfileBindings,
      setProfileRecordArchive,
      setProfileRecordsLoaded,
      setPublicProfileRecordArchives,
      setState,
      setTeamRecordArchives,
      settingsAuthUserIdRef,
      stateRef,
      submitCourtDetailReview,
      submitReportServer,
      syncMatchServer,
      syncRecruitingPostServer,
      syncRefereeServer,
      syncSettingsServer,
      syncTeamInvitationServer,
      syncTeamServer,
      syncTournamentServer,
      teamRecordArchivesRef,
      themeCommittedValueRef,
      themeMutationVersionRef,
    }),
    [applyFavoriteToggle, authEmail, authUserId, currentUserId, deleteTeamServer, ensureRemoteReady, ensureServerActionAvailable, loadAdminContext, loadAdminSection, loadCourtDetail, loadDirectory, loadMatchDetail, loadMatchRecruitingSchedule, loadMatchTeamSchedule, loadMoreMatches, loadMoreRecruiting, loadNotifications, loadRecruitingRegion, loadRecruitingPost, loadPlayMatches, loadReportableMatches, loadProfileRecords, loadPublicProfileRecords, loadTeamRecords, profileRecordsLoaded, markNotificationReadServer, persistProfileServer, profileKey, profileLocked, refreshAdminState, refreshCurrentProfile, runServerAction, serverProfileBound, submitCourtDetailReview, submitReportServer, syncMatchServer, syncRecruitingPostServer, syncRefereeServer, syncSettingsServer, syncTeamInvitationServer, syncTeamServer, syncTournamentServer],
  );

  const safeCurrentUserId = currentUserId ?? currentUser?.id ?? "";
  const safeCurrentUser = currentUser
    ? { ...currentUser, representativeTeamId: state.settings?.representativeTeamId ?? currentUser.representativeTeamId ?? "" }
    : createProfileShell(authUserId ?? safeCurrentUserId, authEmail);
  const matchEntities = useMemo(() => getMatchEntityMap(state.matches), [state.matches]);
  return {
    state: { ...state, currentUserId: safeCurrentUserId || safeCurrentUser.id },
    matchEntities,
    matchLists,
    currentUser: safeCurrentUser,
    currentUserId: safeCurrentUserId || safeCurrentUser.id,
    profileBound: true,
    profileLocked,
    remoteReady,
    serverBusy: serverActionPendingCount > 0,
    adminContext,
    adminState,
    adminStatus,
    matchPagination,
    recruitingPagination,
    directoryStatus,
    recordArchives: {
      profile: profileRecordArchive,
      publicProfiles: publicProfileRecordArchives,
      teams: teamRecordArchives,
    },
    rankings,
    actions,
  };

}
