import {
  DISPUTE_WINDOW_MINUTES,
  MODE_SIZES,
  REFEREE_TRUST_MIN,
  STAT_ENTRY_WINDOW_MINUTES,
} from "../constants.js";

// P-DEMO-CLEANUP: seed/local-dev only. Production app must not import this module.
export const DEMO_TODAY = "2026-06-18";
export const DEMO_NOW = "2026-06-18T12:00:00";
export const DEMO_QUEUE_START = "2026-06-18";
export const DEMO_QUEUE_TIMES = ["18:00", "19:30", "21:00"];
export const DEMO_PRACTICE_COURT = Object.freeze({
  id: "practice-court",
  name: "연습 경기 구장",
});
export const DELETED_SYNTHETIC_COURT_IDS = new Set(
  Array.from({ length: 12 }, (_item, index) => `c${index + 1}`),
);

export function getDemoQueueSlot(slotIndex) {
  const date = new Date(`${DEMO_QUEUE_START}T00:00:00`);
  date.setDate(date.getDate() + Math.floor(slotIndex / DEMO_QUEUE_TIMES.length));
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  const scheduledDate = `${year}-${month}-${day}`;
  const scheduledTime = DEMO_QUEUE_TIMES[slotIndex % DEMO_QUEUE_TIMES.length];
  return {
    scheduledDate,
    scheduledTime,
    scheduledAt: `${scheduledDate} ${scheduledTime}`,
  };
}

export function makeDemoTimestamp(scheduledDate, scheduledTime, extraMinutes = 0) {
  const date = new Date(`${scheduledDate}T${scheduledTime}`);
  date.setMinutes(date.getMinutes() + extraMinutes);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  return `${year}-${month}-${day}T${hours}:${minutes}:00.000Z`;
}

export function makeRelativeDemoDateTime(extraMinutes = 0) {
  const date = new Date();
  date.setSeconds(0, 0);
  date.setMinutes(date.getMinutes() + extraMinutes);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  const scheduledDate = `${year}-${month}-${day}`;
  const scheduledTime = `${hours}:${minutes}`;
  return {
    scheduledDate,
    scheduledTime,
    scheduledAt: `${scheduledDate} ${scheduledTime}`,
    iso: `${scheduledDate}T${scheduledTime}:00.000`,
  };
}

export function getDemoModeSize(mode) {
  return MODE_SIZES[mode] ?? 5;
}

export function getTeamDemoPlayerIds(team = {}, capacity = 5) {
  return (team.members ?? [])
    .map((member) => member.userId)
    .slice(0, capacity);
}

export function makeTrustFeedback(stars = {}) {
  return { stars, updatedAt: null };
}

export function makeDefaultRoomState(chatMessages = []) {
  return {
    chatMessages,
    kickLog: [],
    hostPenalties: [],
    invitations: [],
    partyReserves: {},
    reserveReady: {},
    pinnedReservePlayers: {},
    slotPositions: {},
    ruleRevision: 1,
    approvalModeA: "leader",
    approvalModeB: "leader",
  };
}

export function makeDemoStatSubmissions(teamAPlayers = [], teamBPlayers = [], submittedAt, source = "player", by = null) {
  const rows = [
    ...teamAPlayers.map((playerId) => [playerId, { by: by ?? playerId, side: "teamA", source, submittedAt }]),
    ...teamBPlayers.map((playerId) => [playerId, { by: by ?? playerId, side: "teamB", source, submittedAt }]),
  ];
  return Object.fromEntries(rows);
}

export function makeDemoApplicant({
  kind = "player",
  playerId = null,
  teamId = null,
  side = "teamB",
  status = "waiting",
  reserve = false,
  position = null,
  playerIds = [],
  createdAt = "2026-06-15T09:00:00.000Z",
} = {}) {
  const joinMode = kind === "team" || teamId ? "team" : "player";
  return {
    kind: joinMode,
    joinMode,
    playerId,
    teamId: joinMode === "team" ? teamId : null,
    side,
    status,
    reserve,
    position,
    playerIds: joinMode === "team" ? playerIds : [],
    createdAt,
    updatedAt: createdAt,
  };
}

export const baseState = {
  currentUserId: "u1",
  users: [
    {
      id: "u1",
      name: "민준",
      handle: "#minjun",
      hashtag: "#minjun",
      position: "PG",
      region: "마포",
      school: "연희대",
      company: "프리랜서",
      club: "노을농구회",
      trustScore: 94,
      streak: 3,
      avatarColor: "#58d2c0",
      ratings: { integrated: 1378, modes: { "1v1": 1180, "2v2": 1264, "3v3": 1330, "5v5": 1412 } },
    },
    {
      id: "u2",
      name: "서윤",
      handle: "#seoyun",
      hashtag: "#seoyun",
      position: "SG",
      region: "마포",
      school: "연희대",
      company: "라임랩",
      club: "노을농구회",
      trustScore: 91,
      streak: 1,
      avatarColor: "#f4c74f",
      ratings: { integrated: 1322, modes: { "1v1": 1085, "2v2": 1222, "3v3": 1302, "5v5": 1368 } },
    },
    {
      id: "u3",
      name: "지후",
      handle: "#jihoo",
      hashtag: "#jihoo",
      position: "SF",
      region: "마포",
      school: "동교고",
      company: "라임랩",
      club: "노을농구회",
      trustScore: 86,
      streak: 0,
      avatarColor: "#ff8a5b",
      ratings: { integrated: 1288, modes: { "1v1": 1160, "2v2": 1190, "3v3": 1276, "5v5": 1312 } },
    },
    {
      id: "u4",
      name: "태오",
      handle: "#taeo",
      hashtag: "#taeo",
      position: "PF",
      region: "마포",
      school: "연희대",
      company: "오픈코트",
      club: "노을농구회",
      trustScore: 88,
      streak: 2,
      avatarColor: "#74a8ff",
      ratings: { integrated: 1420, modes: { "1v1": 1240, "2v2": 1320, "3v3": 1398, "5v5": 1456 } },
    },
    {
      id: "u5",
      name: "하린",
      handle: "#harin",
      hashtag: "#harin",
      position: "C",
      region: "마포",
      school: "서강대",
      company: "오픈코트",
      club: "노을농구회",
      trustScore: 90,
      streak: 0,
      avatarColor: "#d98cff",
      ratings: { integrated: 1351, modes: { "1v1": 1010, "2v2": 1250, "3v3": 1322, "5v5": 1402 } },
    },
    {
      id: "u6",
      name: "도윤",
      handle: "#doyun",
      hashtag: "#doyun",
      position: "PG",
      region: "성수",
      school: "건대",
      company: "스틸픽",
      club: "브릿지볼",
      trustScore: 83,
      streak: -1,
      avatarColor: "#ff6f61",
      ratings: { integrated: 1295, modes: { "1v1": 1214, "2v2": 1248, "3v3": 1306, "5v5": 1280 } },
    },
    {
      id: "u7",
      name: "나은",
      handle: "#naeun",
      hashtag: "#naeun",
      position: "SG",
      region: "성수",
      school: "건대",
      company: "스틸픽",
      club: "브릿지볼",
      trustScore: 87,
      streak: 2,
      avatarColor: "#7bd389",
      ratings: { integrated: 1256, modes: { "1v1": 1110, "2v2": 1188, "3v3": 1228, "5v5": 1300 } },
    },
    {
      id: "u8",
      name: "현우",
      handle: "#hyunwoo",
      hashtag: "#hyunwoo",
      position: "SF",
      region: "성수",
      school: "한양대",
      company: "플레이메이트",
      club: "브릿지볼",
      trustScore: 79,
      streak: 0,
      avatarColor: "#f05d5e",
      ratings: { integrated: 1214, modes: { "1v1": 1155, "2v2": 1196, "3v3": 1208, "5v5": 1220 } },
    },
    {
      id: "u9",
      name: "유나",
      handle: "#yuna",
      hashtag: "#yuna",
      position: "PF",
      region: "성수",
      school: "한양대",
      company: "플레이메이트",
      club: "브릿지볼",
      trustScore: 85,
      streak: 1,
      avatarColor: "#ffc857",
      ratings: { integrated: 1340, modes: { "1v1": 1190, "2v2": 1288, "3v3": 1344, "5v5": 1360 } },
    },
    {
      id: "u10",
      name: "시온",
      handle: "#sion",
      hashtag: "#sion",
      position: "C",
      region: "성수",
      school: "건대",
      company: "스틸픽",
      club: "브릿지볼",
      trustScore: 82,
      streak: -2,
      avatarColor: "#8ac7db",
      ratings: { integrated: 1272, modes: { "1v1": 1040, "2v2": 1210, "3v3": 1262, "5v5": 1326 } },
    },
  ],
  teams: [
    {
      id: "t1",
      name: "Noeul Kings",
      homeCourt: "한강 노을코트",
      region: "마포",
      mmr: 1395,
      wins: 18,
      losses: 9,
      accent: "#58d2c0",
      favorite: true,
      members: [
        { userId: "u1", role: "captain" },
        { userId: "u2", role: "regular" },
        { userId: "u3", role: "candidate" },
        { userId: "u4", role: "regular" },
        { userId: "u5", role: "regular" },
      ],
    },
    {
      id: "t2",
      name: "Bridge Ballers",
      homeCourt: "성수 브릿지파크",
      region: "성수",
      mmr: 1318,
      wins: 14,
      losses: 11,
      accent: "#ff6f61",
      favorite: true,
      members: [
        { userId: "u6", role: "captain" },
        { userId: "u7", role: "regular" },
        { userId: "u8", role: "regular" },
        { userId: "u9", role: "regular" },
        { userId: "u10", role: "mercenary" },
      ],
    },
    {
      id: "t3",
      name: "Hongdae Rimfire",
      homeCourt: "홍대 스트릿돔",
      region: "마포",
      mmr: 1284,
      wins: 11,
      losses: 8,
      accent: "#ffd36c",
      favorite: true,
      members: [
        { userId: "u2", role: "captain" },
        { userId: "u1", role: "regular" },
        { userId: "u5", role: "regular" },
        { userId: "u8", role: "mercenary" },
        { userId: "u3", role: "candidate" },
      ],
    },
    {
      id: "t4",
      name: "Ttukseom Flow",
      homeCourt: "뚝섬 리버사이드",
      region: "성수",
      mmr: 1268,
      wins: 10,
      losses: 10,
      accent: "#46e0b6",
      favorite: true,
      members: [
        { userId: "u7", role: "captain" },
        { userId: "u6", role: "regular" },
        { userId: "u9", role: "regular" },
        { userId: "u13", role: "guest" },
      ],
    },
    {
      id: "t5",
      name: "Jamsil Meteors",
      homeCourt: "잠실 실내체육관 보조코트",
      region: "잠실",
      mmr: 1442,
      wins: 22,
      losses: 7,
      accent: "#76a9ff",
      favorite: true,
      members: [
        { userId: "u4", role: "captain" },
        { userId: "u33", role: "regular" },
        { userId: "u10", role: "regular" },
        { userId: "u34", role: "mercenary" },
      ],
    },
    {
      id: "t6",
      name: "Gangnam Switch",
      homeCourt: "양재 플로우코트",
      region: "강남",
      mmr: 1336,
      wins: 16,
      losses: 13,
      accent: "#c792ff",
      favorite: true,
      members: [
        { userId: "u11", role: "captain" },
        { userId: "u12", role: "regular" },
        { userId: "u13", role: "candidate" },
        { userId: "u14", role: "regular" },
      ],
    },
    {
      id: "t7",
      name: "Banpo Arc",
      homeCourt: "반포 선셋파크",
      region: "서초",
      mmr: 1248,
      wins: 9,
      losses: 12,
      accent: "#ffab4c",
      favorite: true,
      members: [
        { userId: "u15", role: "captain" },
        { userId: "u16", role: "regular" },
        { userId: "u17", role: "candidate" },
      ],
    },
    {
      id: "t8",
      name: "Noryangjin Press",
      homeCourt: "노량진 루프코트",
      region: "동작",
      mmr: 1198,
      wins: 8,
      losses: 14,
      accent: "#ff755f",
      favorite: true,
      members: [
        { userId: "u18", role: "captain" },
        { userId: "u19", role: "regular" },
        { userId: "u20", role: "guest" },
      ],
    },
    {
      id: "t9",
      name: "Yeonnam Rails",
      homeCourt: "연남 레일파크",
      region: "마포",
      mmr: 1226,
      wins: 12,
      losses: 16,
      accent: "#8ac7db",
      favorite: false,
      members: [
        { userId: "u21", role: "captain" },
        { userId: "u22", role: "regular" },
        { userId: "u23", role: "mercenary" },
      ],
    },
    {
      id: "t10",
      name: "Mullae Iron",
      homeCourt: "문래 팩토리코트",
      region: "영등포",
      mmr: 1302,
      wins: 15,
      losses: 13,
      accent: "#9aa4b2",
      favorite: false,
      members: [
        { userId: "u24", role: "captain" },
        { userId: "u25", role: "regular" },
        { userId: "u26", role: "candidate" },
      ],
    },
    {
      id: "t11",
      name: "Wangsimni Breakers",
      homeCourt: "왕십리 언더패스",
      region: "성동",
      mmr: 1176,
      wins: 7,
      losses: 15,
      accent: "#f05d5e",
      favorite: false,
      members: [
        { userId: "u27", role: "captain" },
        { userId: "u28", role: "regular" },
        { userId: "u29", role: "regular" },
      ],
    },
    {
      id: "t12",
      name: "Sinchon Blue",
      homeCourt: "신촌 블루짐",
      region: "서대문",
      mmr: 1210,
      wins: 10,
      losses: 14,
      accent: "#74a8ff",
      favorite: false,
      members: [
        { userId: "u30", role: "captain" },
        { userId: "u31", role: "regular" },
        { userId: "u32", role: "guest" },
      ],
    },
  ],
  affiliations: [
    { id: "a1", type: "region", name: "마포", score: 1420, wins: 38, losses: 24 },
    { id: "a2", type: "region", name: "성수", score: 1362, wins: 32, losses: 27 },
    { id: "a3", type: "school", name: "연희대", score: 1398, wins: 21, losses: 13 },
    { id: "a4", type: "company", name: "스틸픽", score: 1298, wins: 17, losses: 16 },
  ],
  seasons: [
    {
      id: "season-zero",
      name: "Season Zero",
      subtitle: "지역 래더와 승인 시스템을 검증하는 프리시즌",
      startsAt: "2026-05-31",
      endsAt: "2026-08-31",
      active: true,
      regions: ["마포", "성수", "잠실", "강남"],
      promotionLine: 4,
      rules: [
        "지역 랭킹은 같은 지역 플레이어를 먼저 정렬합니다.",
        "정규전은 티어 구간 제한과 경기 운영 권한 검증을 통과해야 합니다.",
        "일반 경기 최종 승인은 심판 경기의 배정 심판, 무심판 경기의 방장이 처리합니다.",
      ],
    },
  ],
  matches: [
    {
      id: "m-live-clock",
      title: "Clock Live 3v3 · Hongdae Rimfire vs Bridge Ballers",
      mode: "3v3",
      court: "Clock Test Court",
      scheduledDate: "2026-06-16",
      scheduledTime: "00:00",
      scheduledAt: "2026-06-16 00:00",
      status: "agreed",
      official: false,
      preRegistered: true,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      rules: { targetScore: 21, timeLimit: 1440, winByTwo: false, ball: "7호" },
      memo: "경기시계 담당자 권한 검증용 live demo.",
      stakes: "Demo match for live clock access.",
      ranked: true,
      objectionWindow: "2시간",
      evidence: [],
      teamA: { name: "Hongdae Rimfire", teamId: "t3", players: ["u2", "u5", "u8"], score: 0 },
      teamB: { name: "Bridge Ballers", teamId: "t2", players: ["u6", "u7", "u9"], score: 0 },
      parties: [
        { kind: "team", side: "teamA", teamId: "t3", playerId: "u2", players: ["u2", "u5", "u8"], reserves: ["u1", "u3"], reserve: false },
        { kind: "team", side: "teamB", teamId: "t2", playerId: "u6", players: ["u6", "u7", "u9"], reserves: ["u10"], reserve: false },
      ],
      reservePlayers: { teamA: ["u1", "u3"], teamB: ["u10"] },
      promotedReserveIds: { teamA: [], teamB: [] },
      agreements: { teamA: ["u2", "u5", "u8"], teamB: ["u6", "u7", "u9"] },
      approvals: { teamA: [], teamB: [] },
      disputes: [],
      result: null,
      ratingResult: null,
      teamRatingResult: null,
      endedAt: null,
      trustFeedback: makeTrustFeedback(),
      createdAt: "2026-06-15T12:00:00.000Z",
      agreedAt: "2026-06-15T12:10:00.000Z",
      confirmedAt: null,
    },
    {
      id: "m1",
      title: "토요 5v5 공식전",
      mode: "5v5",
      court: "한강 노을코트",
      scheduledDate: "2026-06-18",
      scheduledTime: "20:30",
      scheduledAt: "2026-06-18 20:30",
      status: "contract",
      official: true,
      preRegistered: true,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      rules: { targetScore: 21, timeLimit: 12, winByTwo: true, ball: "7호 공" },
      memo: "승자팀 다음 경기 우선권. 금전 거래 없이 약속만 기록합니다.",
      stakes: "승자팀 다음 경기 우선권. 금전 거래 없이 약속만 기록합니다.",
      ranked: true,
      objectionWindow: "24시간",
      evidence: [{ id: "court_reservation", label: "구장 예약내역" }],
      teamA: { name: "Noeul Kings", teamId: "t1", players: ["u1", "u2", "u3", "u4", "u5"], score: 0 },
      teamB: { name: "Bridge Ballers", teamId: "t2", players: ["u6", "u7", "u8", "u9", "u10"], score: 0 },
      agreements: { teamA: [], teamB: [] },
      approvals: { teamA: [], teamB: [] },
      disputes: [],
      result: null,
      ratingResult: null,
      teamRatingResult: null,
      endedAt: null,
      trustFeedback: makeTrustFeedback(),
      createdAt: "2026-06-15T10:00:00.000Z",
      confirmedAt: null,
    },
    {
      id: "m0",
      title: "성수 3v3 리벤지",
      mode: "3v3",
      court: "성수 브릿지파크",
      scheduledDate: "2026-05-30",
      scheduledTime: "21:00",
      scheduledAt: "2026-05-30 21:00",
      status: "confirmed",
      official: false,
      preRegistered: true,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      rules: { targetScore: 15, timeLimit: 10, winByTwo: false, ball: "7호 공" },
      memo: "빠른 입력 테스트용 기록",
      stakes: "리벤지 매치. 패자는 다음 판 물/음료 준비.",
      evidence: [],
      ranked: true,
      objectionWindow: "1시간",
      teamA: { name: "Noeul Kings", teamId: "t1", players: ["u1", "u2", "u4"], score: 15 },
      teamB: { name: "Bridge Ballers", teamId: "t2", players: ["u6", "u7", "u9"], score: 12 },
      agreements: { teamA: ["u1", "u2"], teamB: ["u6", "u7"] },
      approvals: { teamA: ["u1", "u2"], teamB: ["u6", "u7"] },
      disputes: [],
      result: {
        scoreA: 15,
        scoreB: 12,
        playerStats: {
          u1: { points: 6, rebounds: 2, assists: 5, steals: 1, blocks: 0 },
          u2: { points: 5, rebounds: 3, assists: 2, steals: 2, blocks: 0 },
          u4: { points: 4, rebounds: 6, assists: 1, steals: 0, blocks: 1 },
          u6: { points: 4, rebounds: 2, assists: 4, steals: 1, blocks: 0 },
          u7: { points: 3, rebounds: 4, assists: 2, steals: 1, blocks: 0 },
          u9: { points: 5, rebounds: 5, assists: 1, steals: 0, blocks: 1 },
        },
        statSubmissions: makeDemoStatSubmissions(["u1", "u2", "u4"], ["u6", "u7", "u9"], "2026-05-30T12:20:00.000Z"),
        submittedBy: "u1",
        submittedAt: "2026-05-30T12:20:00.000Z",
        updatedAt: "2026-05-30T12:20:00.000Z",
      },
      ratingResult: [
        { playerId: "u1", integratedDelta: 12.2, modeDelta: 15.8, result: "win" },
        { playerId: "u6", integratedDelta: -10.6, modeDelta: -13.9, result: "loss" },
      ],
      teamRatingResult: { teamA: 12, teamB: -11 },
      endedAt: "2026-05-30T12:10:00.000Z",
      trustFeedback: makeTrustFeedback({ u1: ["u6"], u6: ["u1"] }),
      createdAt: "2026-05-30T11:10:00.000Z",
      confirmedAt: "2026-05-30T12:25:00.000Z",
    },
  ],
  notifications: [
    { id: "n-invite-q2-u1", title: "매치방 초대", body: "성수 친선 3v3 팀 구해요 A사이드 빈 슬롯 초대장이 도착했습니다.", tone: "match", targetUserId: "u1", recruitingPostId: "q2" },
    { id: "n1", title: "경기 전 동의 대기", body: "토요 5v5 공식전의 경기 전 동의를 기다리고 있습니다.", tone: "match", matchId: "m1" },
    { id: "n2", title: "3연승", body: "민준의 통합 티어가 Platinum에 가까워지고 있어요.", tone: "tier" },
  ],
  tournaments: [],
  recruitingPosts: [
    {
      id: "q1",
      type: "need_player",
      title: "Noeul Kings 5v5 용병 1명",
      region: "마포",
      court: "한강 노을코트",
      mode: "5v5",
      ...getDemoQueueSlot(0),
      ranked: true,
      spots: 6,
      teamId: "t1",
      targetTeamId: null,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      hostJoinMode: "team",
      hostSide: "teamA",
      hostReady: false,
      sideCapacity: 5,
      playerIds: ["u1", "u2", "u4", "u5"],
      position: "PF",
      playerId: "u1",
      memo: "리바운드 같이 잡아줄 포워드/센터면 좋아요.",
      status: "open",
      applicants: [makeDemoApplicant({ kind: "player", playerId: "u8", side: "teamB", status: "waiting", position: "SF", createdAt: "2026-06-15T09:44:00.000Z" })],
      roomState: makeDefaultRoomState([{ id: "chat-q1-1", userId: "u1", body: "Need one more player for teamB.", createdAt: "2026-06-15T09:35:00.000Z" }]),
      createdAt: "2026-06-15T09:30:00.000Z",
    },
    {
      id: "q2",
      type: "find_team",
      title: "성수 친선 3v3 팀 구해요",
      region: "성수",
      court: "성수 브릿지파크",
      mode: "3v3",
      ...getDemoQueueSlot(1),
      ranked: false,
      spots: 5,
      teamId: null,
      targetTeamId: null,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      hostJoinMode: "player",
      hostSide: "teamA",
      hostReady: false,
      sideCapacity: 3,
      playerIds: [],
      position: "SG",
      playerId: "u9",
      memo: "티어 상관없이 빠르게 두세 판 뛸 팀 찾습니다.",
      status: "open",
      applicants: [makeDemoApplicant({ kind: "team", teamId: "t2", playerId: "u6", side: "teamB", status: "ready", playerIds: ["u6", "u7", "u8"], createdAt: "2026-06-15T08:55:00.000Z" })],
      roomState: {
        ...makeDefaultRoomState([{ id: "chat-q2-1", userId: "u6", body: "Team party can fill the opposite side.", createdAt: "2026-06-15T08:57:00.000Z" }]),
        demoInviteQ2Seeded: true,
        invitations: [
          {
            id: "inv-demo-q2-u1",
            targetUserId: "u1",
            fromUserId: "u9",
            teamId: null,
            side: "teamA",
            reserve: false,
            status: "pending",
            createdAt: "2026-06-15T09:05:00.000Z",
            updatedAt: "2026-06-15T09:05:00.000Z",
          },
        ],
      },
      createdAt: "2026-06-15T08:40:00.000Z",
    },
    {
      id: "q3",
      type: "need_player",
      title: "잠실 5v5 공식전 가드 대타",
      region: "잠실",
      court: "잠실 실내체육관 보조코트",
      mode: "5v5",
      ...getDemoQueueSlot(2),
      ranked: true,
      spots: 6,
      teamId: "t5",
      targetTeamId: null,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      hostJoinMode: "team",
      hostSide: "teamA",
      hostReady: true,
      sideCapacity: 5,
      playerIds: ["u4", "u5", "u10", "u1"],
      position: "PG",
      playerId: "u4",
      memo: "볼 운반이 가능한 가드는 포지션 제한이 없습니다.",
      status: "open",
      applicants: [makeDemoApplicant({ kind: "player", playerId: "u2", side: "teamB", status: "ready", position: "SG", createdAt: "2026-06-15T08:05:00.000Z" })],
      roomState: makeDefaultRoomState([{ id: "chat-q3-1", userId: "u4", body: "Ready when the opposite side fills.", createdAt: "2026-06-15T08:00:00.000Z" }]),
      createdAt: "2026-06-15T07:55:00.000Z",
    },
    {
      id: "q4",
      type: "need_team",
      title: "마포 정규전 5v5 상대팀 구해요",
      region: "마포",
      court: "홍대 스트릿돔",
      mode: "5v5",
      ...getDemoQueueSlot(3),
      ranked: true,
      spots: 6,
      teamId: "t1",
      targetTeamId: null,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      hostJoinMode: "team",
      hostSide: "teamA",
      hostReady: false,
      sideCapacity: 5,
      playerIds: ["u1", "u2", "u4", "u5"],
      position: "상관없음",
      playerId: "u1",
      memo: "비슷한 티어의 팀과 경기방을 만들고 양 팀 동의 후 진행합니다.",
      status: "open",
      applicants: [makeDemoApplicant({ kind: "team", teamId: "t3", playerId: "u2", side: "teamB", status: "waiting", playerIds: ["u2", "u5", "u8"], createdAt: "2026-06-15T10:10:00.000Z" })],
      roomState: makeDefaultRoomState([{ id: "chat-q4-1", userId: "u2", body: "We can bring three now and keep reserves open.", createdAt: "2026-06-15T10:12:00.000Z" }]),
      createdAt: "2026-06-15T10:00:00.000Z",
    },
  ],
  settings: {
    theme: "dark",
    privacy: {
      regionRanking: true,
      teamHistory: true,
      statSummary: true,
    },
    blockedUserIds: [],
    favoritePlayerIds: ["u2", "u3", "u4"],
    favoriteTeamIds: ["t1", "t2", "t5"],
    favoriteCourtIds: [],
    favoriteRefereeIds: ["u11"],
  },
  reports: [],
};
