import { DISPUTE_WINDOW_MINUTES, MODE_SIZES, REFEREE_TRUST_MIN, STAT_ENTRY_WINDOW_MINUTES } from "../constants.js";
import { DEMO_TODAY, DEMO_NOW, DEMO_QUEUE_START, DEMO_QUEUE_TIMES, DEMO_PRACTICE_COURT, DELETED_SYNTHETIC_COURT_IDS, getDemoQueueSlot, makeDemoTimestamp, makeRelativeDemoDateTime, getDemoModeSize, getTeamDemoPlayerIds, makeTrustFeedback, makeDefaultRoomState, makeDemoStatSubmissions, makeDemoApplicant } from "./baseStateHelpers.js";

export const baseAffiliations = [
    { id: "a1", type: "region", name: "마포", score: 1420, wins: 38, losses: 24 },
    { id: "a2", type: "region", name: "성수", score: 1362, wins: 32, losses: 27 },
    { id: "a3", type: "school", name: "연희대", score: 1398, wins: 21, losses: 13 },
    { id: "a4", type: "company", name: "스틸픽", score: 1298, wins: 17, losses: 16 },
  ];

export const baseSeasons = [
    {
      id: "season-zero",
      name: "Season Zero",
      subtitle: "지역 래더와 승인 시스템을 검증하는 프리시즌",
      startsAt: "2026-05-31",
      endsAt: "2026-08-31",
      active: true,
      regions: ["마포", "성수", "잠실", "강남"],
      promotionLine: 4,
      rules: [
        "지역 랭킹은 같은 지역 플레이어를 먼저 정렬합니다.",
        "정규전은 티어 구간 제한과 경기 운영 권한 검증을 통과해야 합니다.",
        "일반 경기 최종 승인은 심판 경기의 배정 심판, 무심판 경기의 방장이 처리합니다.",
      ],
    },
  ];

export const baseMatches = [
    {
      id: "m-live-clock",
      title: "Clock Live 3v3 · Hongdae Rimfire vs Bridge Ballers",
      mode: "3v3",
      court: "Clock Test Court",
      scheduledDate: "2026-06-16",
      scheduledTime: "00:00",
      scheduledAt: "2026-06-16 00:00",
      status: "agreed",
      official: false,
      preRegistered: true,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      rules: { targetScore: 21, timeLimit: 1440, winByTwo: false, ball: "7호" },
      memo: "경기시계 담당자 권한 검증용 live demo.",
      stakes: "Demo match for live clock access.",
      ranked: true,
      objectionWindow: "2시간",
      evidence: [],
      teamA: { name: "Hongdae Rimfire", teamId: "t3", players: ["u2", "u5", "u8"], score: 0 },
      teamB: { name: "Bridge Ballers", teamId: "t2", players: ["u6", "u7", "u9"], score: 0 },
      parties: [
        { kind: "team", side: "teamA", teamId: "t3", playerId: "u2", players: ["u2", "u5", "u8"], reserves: ["u1", "u3"], reserve: false },
        { kind: "team", side: "teamB", teamId: "t2", playerId: "u6", players: ["u6", "u7", "u9"], reserves: ["u10"], reserve: false },
      ],
      reservePlayers: { teamA: ["u1", "u3"], teamB: ["u10"] },
      promotedReserveIds: { teamA: [], teamB: [] },
      agreements: { teamA: ["u2", "u5", "u8"], teamB: ["u6", "u7", "u9"] },
      approvals: { teamA: [], teamB: [] },
      disputes: [],
      result: null,
      ratingResult: null,
      teamRatingResult: null,
      endedAt: null,
      trustFeedback: makeTrustFeedback(),
      createdAt: "2026-06-15T12:00:00.000Z",
      agreedAt: "2026-06-15T12:10:00.000Z",
      confirmedAt: null,
    },
    {
      id: "m1",
      title: "토요 5v5 공식전",
      mode: "5v5",
      court: "한강 노을코트",
      scheduledDate: "2026-06-18",
      scheduledTime: "20:30",
      scheduledAt: "2026-06-18 20:30",
      status: "contract",
      official: true,
      preRegistered: true,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      rules: { targetScore: 21, timeLimit: 12, winByTwo: true, ball: "7호 공" },
      memo: "승자팀 다음 경기 우선권. 금전 거래 없이 약속만 기록합니다.",
      stakes: "승자팀 다음 경기 우선권. 금전 거래 없이 약속만 기록합니다.",
      ranked: true,
      objectionWindow: "24시간",
      evidence: [{ id: "court_reservation", label: "구장 예약내역" }],
      teamA: { name: "Noeul Kings", teamId: "t1", players: ["u1", "u2", "u3", "u4", "u5"], score: 0 },
      teamB: { name: "Bridge Ballers", teamId: "t2", players: ["u6", "u7", "u8", "u9", "u10"], score: 0 },
      agreements: { teamA: [], teamB: [] },
      approvals: { teamA: [], teamB: [] },
      disputes: [],
      result: null,
      ratingResult: null,
      teamRatingResult: null,
      endedAt: null,
      trustFeedback: makeTrustFeedback(),
      createdAt: "2026-06-15T10:00:00.000Z",
      confirmedAt: null,
    },
    {
      id: "m0",
      title: "성수 3v3 리벤지",
      mode: "3v3",
      court: "성수 브릿지파크",
      scheduledDate: "2026-05-30",
      scheduledTime: "21:00",
      scheduledAt: "2026-05-30 21:00",
      status: "confirmed",
      official: false,
      preRegistered: true,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      rules: { targetScore: 15, timeLimit: 10, winByTwo: false, ball: "7호 공" },
      memo: "빠른 입력 테스트용 기록",
      stakes: "리벤지 매치. 패자는 다음 판 물/음료 준비.",
      evidence: [],
      ranked: true,
      objectionWindow: "1시간",
      teamA: { name: "Noeul Kings", teamId: "t1", players: ["u1", "u2", "u4"], score: 15 },
      teamB: { name: "Bridge Ballers", teamId: "t2", players: ["u6", "u7", "u9"], score: 12 },
      agreements: { teamA: ["u1", "u2"], teamB: ["u6", "u7"] },
      approvals: { teamA: ["u1", "u2"], teamB: ["u6", "u7"] },
      disputes: [],
      result: {
        scoreA: 15,
        scoreB: 12,
        playerStats: {
          u1: { points: 6, rebounds: 2, assists: 5, steals: 1, blocks: 0 },
          u2: { points: 5, rebounds: 3, assists: 2, steals: 2, blocks: 0 },
          u4: { points: 4, rebounds: 6, assists: 1, steals: 0, blocks: 1 },
          u6: { points: 4, rebounds: 2, assists: 4, steals: 1, blocks: 0 },
          u7: { points: 3, rebounds: 4, assists: 2, steals: 1, blocks: 0 },
          u9: { points: 5, rebounds: 5, assists: 1, steals: 0, blocks: 1 },
        },
        statSubmissions: makeDemoStatSubmissions(["u1", "u2", "u4"], ["u6", "u7", "u9"], "2026-05-30T12:20:00.000Z"),
        submittedBy: "u1",
        submittedAt: "2026-05-30T12:20:00.000Z",
        updatedAt: "2026-05-30T12:20:00.000Z",
      },
      ratingResult: [
        { playerId: "u1", integratedDelta: 12.2, modeDelta: 15.8, result: "win" },
        { playerId: "u6", integratedDelta: -10.6, modeDelta: -13.9, result: "loss" },
      ],
      teamRatingResult: { teamA: 12, teamB: -11 },
      endedAt: "2026-05-30T12:10:00.000Z",
      trustFeedback: makeTrustFeedback({ u1: ["u6"], u6: ["u1"] }),
      createdAt: "2026-05-30T11:10:00.000Z",
      confirmedAt: "2026-05-30T12:25:00.000Z",
    },
  ];

export const baseNotifications = [
    { id: "n-invite-q2-u1", title: "매치방 초대", body: "성수 친선 3v3 팀 구해요 A사이드 빈 슬롯 초대장이 도착했습니다.", tone: "match", targetUserId: "u1", recruitingPostId: "q2" },
    { id: "n1", title: "경기 전 동의 대기", body: "토요 5v5 공식전의 경기 전 동의를 기다리고 있습니다.", tone: "match", matchId: "m1" },
    { id: "n2", title: "3연승", body: "민준의 통합 티어가 Platinum에 가까워지고 있어요.", tone: "tier" },
  ];

export const baseTournaments = [];

export const baseRecruitingPosts = [
    {
      id: "q1",
      type: "need_player",
      title: "Noeul Kings 5v5 용병 1명",
      region: "마포",
      court: "한강 노을코트",
      mode: "5v5",
      ...getDemoQueueSlot(0),
      ranked: true,
      spots: 6,
      teamId: "t1",
      targetTeamId: null,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      hostJoinMode: "team",
      hostSide: "teamA",
      hostReady: false,
      sideCapacity: 5,
      playerIds: ["u1", "u2", "u4", "u5"],
      position: "PF",
      playerId: "u1",
      memo: "리바운드 같이 잡아줄 포워드/센터면 좋아요.",
      status: "open",
      applicants: [makeDemoApplicant({ kind: "player", playerId: "u8", side: "teamB", status: "waiting", position: "SF", createdAt: "2026-06-15T09:44:00.000Z" })],
      roomState: makeDefaultRoomState([{ id: "chat-q1-1", userId: "u1", body: "Need one more player for teamB.", createdAt: "2026-06-15T09:35:00.000Z" }]),
      createdAt: "2026-06-15T09:30:00.000Z",
    },
    {
      id: "q2",
      type: "find_team",
      title: "성수 친선 3v3 팀 구해요",
      region: "성수",
      court: "성수 브릿지파크",
      mode: "3v3",
      ...getDemoQueueSlot(1),
      ranked: false,
      spots: 5,
      teamId: null,
      targetTeamId: null,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      hostJoinMode: "player",
      hostSide: "teamA",
      hostReady: false,
      sideCapacity: 3,
      playerIds: [],
      position: "SG",
      playerId: "u9",
      memo: "티어 상관없이 빠르게 두세 판 뛸 팀 찾습니다.",
      status: "open",
      applicants: [makeDemoApplicant({ kind: "team", teamId: "t2", playerId: "u6", side: "teamB", status: "ready", playerIds: ["u6", "u7", "u8"], createdAt: "2026-06-15T08:55:00.000Z" })],
      roomState: {
        ...makeDefaultRoomState([{ id: "chat-q2-1", userId: "u6", body: "Team party can fill the opposite side.", createdAt: "2026-06-15T08:57:00.000Z" }]),
        demoInviteQ2Seeded: true,
        invitations: [
          {
            id: "inv-demo-q2-u1",
            targetUserId: "u1",
            fromUserId: "u9",
            teamId: null,
            side: "teamA",
            reserve: false,
            status: "pending",
            createdAt: "2026-06-15T09:05:00.000Z",
            updatedAt: "2026-06-15T09:05:00.000Z",
          },
        ],
      },
      createdAt: "2026-06-15T08:40:00.000Z",
    },
    {
      id: "q3",
      type: "need_player",
      title: "잠실 5v5 공식전 가드 대타",
      region: "잠실",
      court: "잠실 실내체육관 보조코트",
      mode: "5v5",
      ...getDemoQueueSlot(2),
      ranked: true,
      spots: 6,
      teamId: "t5",
      targetTeamId: null,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      hostJoinMode: "team",
      hostSide: "teamA",
      hostReady: true,
      sideCapacity: 5,
      playerIds: ["u4", "u5", "u10", "u1"],
      position: "PG",
      playerId: "u4",
      memo: "볼 운반이 가능한 가드는 포지션 제한이 없습니다.",
      status: "open",
      applicants: [makeDemoApplicant({ kind: "player", playerId: "u2", side: "teamB", status: "ready", position: "SG", createdAt: "2026-06-15T08:05:00.000Z" })],
      roomState: makeDefaultRoomState([{ id: "chat-q3-1", userId: "u4", body: "Ready when the opposite side fills.", createdAt: "2026-06-15T08:00:00.000Z" }]),
      createdAt: "2026-06-15T07:55:00.000Z",
    },
    {
      id: "q4",
      type: "need_team",
      title: "마포 정규전 5v5 상대팀 구해요",
      region: "마포",
      court: "홍대 스트릿돔",
      mode: "5v5",
      ...getDemoQueueSlot(3),
      ranked: true,
      spots: 6,
      teamId: "t1",
      targetTeamId: null,
      refereeId: "",
      refereeTrustMin: REFEREE_TRUST_MIN,
      statEntryMinutes: STAT_ENTRY_WINDOW_MINUTES,
      disputeMinutes: DISPUTE_WINDOW_MINUTES,
      hostJoinMode: "team",
      hostSide: "teamA",
      hostReady: false,
      sideCapacity: 5,
      playerIds: ["u1", "u2", "u4", "u5"],
      position: "상관없음",
      playerId: "u1",
      memo: "비슷한 티어의 팀과 경기방을 만들고 양 팀 동의 후 진행합니다.",
      status: "open",
      applicants: [makeDemoApplicant({ kind: "team", teamId: "t3", playerId: "u2", side: "teamB", status: "waiting", playerIds: ["u2", "u5", "u8"], createdAt: "2026-06-15T10:10:00.000Z" })],
      roomState: makeDefaultRoomState([{ id: "chat-q4-1", userId: "u2", body: "We can bring three now and keep reserves open.", createdAt: "2026-06-15T10:12:00.000Z" }]),
      createdAt: "2026-06-15T10:00:00.000Z",
    },
  ];

export const baseSettings = {
    theme: "dark",
    privacy: {
      regionRanking: true,
      teamHistory: true,
      statSummary: true,
    },
    blockedUserIds: [],
    favoritePlayerIds: ["u2", "u3", "u4"],
    favoriteTeamIds: ["t1", "t2", "t5"],
    favoriteCourtIds: [],
    favoriteRefereeIds: ["u11"],
  };

export const baseReports = [];
