
export const baseUsers = [
    {
      id: "u1",
      name: "민준",
      handle: "#minjun",
      hashtag: "#minjun",
      position: "PG",
      region: "마포",
      school: "연희대",
      company: "프리랜서",
      club: "노을농구회",
      trustScore: 94,
      streak: 3,
      avatarColor: "#58d2c0",
      ratings: { integrated: 1378, modes: { "1v1": 1180, "2v2": 1264, "3v3": 1330, "5v5": 1412 } },
    },
    {
      id: "u2",
      name: "서윤",
      handle: "#seoyun",
      hashtag: "#seoyun",
      position: "SG",
      region: "마포",
      school: "연희대",
      company: "라임랩",
      club: "노을농구회",
      trustScore: 91,
      streak: 1,
      avatarColor: "#f4c74f",
      ratings: { integrated: 1322, modes: { "1v1": 1085, "2v2": 1222, "3v3": 1302, "5v5": 1368 } },
    },
    {
      id: "u3",
      name: "지후",
      handle: "#jihoo",
      hashtag: "#jihoo",
      position: "SF",
      region: "마포",
      school: "동교고",
      company: "라임랩",
      club: "노을농구회",
      trustScore: 86,
      streak: 0,
      avatarColor: "#ff8a5b",
      ratings: { integrated: 1288, modes: { "1v1": 1160, "2v2": 1190, "3v3": 1276, "5v5": 1312 } },
    },
    {
      id: "u4",
      name: "태오",
      handle: "#taeo",
      hashtag: "#taeo",
      position: "PF",
      region: "마포",
      school: "연희대",
      company: "오픈코트",
      club: "노을농구회",
      trustScore: 88,
      streak: 2,
      avatarColor: "#74a8ff",
      ratings: { integrated: 1420, modes: { "1v1": 1240, "2v2": 1320, "3v3": 1398, "5v5": 1456 } },
    },
    {
      id: "u5",
      name: "하린",
      handle: "#harin",
      hashtag: "#harin",
      position: "C",
      region: "마포",
      school: "서강대",
      company: "오픈코트",
      club: "노을농구회",
      trustScore: 90,
      streak: 0,
      avatarColor: "#d98cff",
      ratings: { integrated: 1351, modes: { "1v1": 1010, "2v2": 1250, "3v3": 1322, "5v5": 1402 } },
    },
    {
      id: "u6",
      name: "도윤",
      handle: "#doyun",
      hashtag: "#doyun",
      position: "PG",
      region: "성수",
      school: "건대",
      company: "스틸픽",
      club: "브릿지볼",
      trustScore: 83,
      streak: -1,
      avatarColor: "#ff6f61",
      ratings: { integrated: 1295, modes: { "1v1": 1214, "2v2": 1248, "3v3": 1306, "5v5": 1280 } },
    },
    {
      id: "u7",
      name: "나은",
      handle: "#naeun",
      hashtag: "#naeun",
      position: "SG",
      region: "성수",
      school: "건대",
      company: "스틸픽",
      club: "브릿지볼",
      trustScore: 87,
      streak: 2,
      avatarColor: "#7bd389",
      ratings: { integrated: 1256, modes: { "1v1": 1110, "2v2": 1188, "3v3": 1228, "5v5": 1300 } },
    },
    {
      id: "u8",
      name: "현우",
      handle: "#hyunwoo",
      hashtag: "#hyunwoo",
      position: "SF",
      region: "성수",
      school: "한양대",
      company: "플레이메이트",
      club: "브릿지볼",
      trustScore: 79,
      streak: 0,
      avatarColor: "#f05d5e",
      ratings: { integrated: 1214, modes: { "1v1": 1155, "2v2": 1196, "3v3": 1208, "5v5": 1220 } },
    },
    {
      id: "u9",
      name: "유나",
      handle: "#yuna",
      hashtag: "#yuna",
      position: "PF",
      region: "성수",
      school: "한양대",
      company: "플레이메이트",
      club: "브릿지볼",
      trustScore: 85,
      streak: 1,
      avatarColor: "#ffc857",
      ratings: { integrated: 1340, modes: { "1v1": 1190, "2v2": 1288, "3v3": 1344, "5v5": 1360 } },
    },
    {
      id: "u10",
      name: "시온",
      handle: "#sion",
      hashtag: "#sion",
      position: "C",
      region: "성수",
      school: "건대",
      company: "스틸픽",
      club: "브릿지볼",
      trustScore: 82,
      streak: -2,
      avatarColor: "#8ac7db",
      ratings: { integrated: 1272, modes: { "1v1": 1040, "2v2": 1210, "3v3": 1262, "5v5": 1326 } },
    },
  ];

export const baseTeams = [
    {
      id: "t1",
      name: "Noeul Kings",
      homeCourt: "한강 노을코트",
      region: "마포",
      mmr: 1395,
      wins: 18,
      losses: 9,
      accent: "#58d2c0",
      favorite: true,
      members: [
        { userId: "u1", role: "captain" },
        { userId: "u2", role: "regular" },
        { userId: "u3", role: "candidate" },
        { userId: "u4", role: "regular" },
        { userId: "u5", role: "regular" },
      ],
    },
    {
      id: "t2",
      name: "Bridge Ballers",
      homeCourt: "성수 브릿지파크",
      region: "성수",
      mmr: 1318,
      wins: 14,
      losses: 11,
      accent: "#ff6f61",
      favorite: true,
      members: [
        { userId: "u6", role: "captain" },
        { userId: "u7", role: "regular" },
        { userId: "u8", role: "regular" },
        { userId: "u9", role: "regular" },
        { userId: "u10", role: "mercenary" },
      ],
    },
    {
      id: "t3",
      name: "Hongdae Rimfire",
      homeCourt: "홍대 스트릿돔",
      region: "마포",
      mmr: 1284,
      wins: 11,
      losses: 8,
      accent: "#ffd36c",
      favorite: true,
      members: [
        { userId: "u2", role: "captain" },
        { userId: "u1", role: "regular" },
        { userId: "u5", role: "regular" },
        { userId: "u8", role: "mercenary" },
        { userId: "u3", role: "candidate" },
      ],
    },
    {
      id: "t4",
      name: "Ttukseom Flow",
      homeCourt: "뚝섬 리버사이드",
      region: "성수",
      mmr: 1268,
      wins: 10,
      losses: 10,
      accent: "#46e0b6",
      favorite: true,
      members: [
        { userId: "u7", role: "captain" },
        { userId: "u6", role: "regular" },
        { userId: "u9", role: "regular" },
        { userId: "u13", role: "guest" },
      ],
    },
    {
      id: "t5",
      name: "Jamsil Meteors",
      homeCourt: "잠실 실내체육관 보조코트",
      region: "잠실",
      mmr: 1442,
      wins: 22,
      losses: 7,
      accent: "#76a9ff",
      favorite: true,
      members: [
        { userId: "u4", role: "captain" },
        { userId: "u33", role: "regular" },
        { userId: "u10", role: "regular" },
        { userId: "u34", role: "mercenary" },
      ],
    },
    {
      id: "t6",
      name: "Gangnam Switch",
      homeCourt: "양재 플로우코트",
      region: "강남",
      mmr: 1336,
      wins: 16,
      losses: 13,
      accent: "#c792ff",
      favorite: true,
      members: [
        { userId: "u11", role: "captain" },
        { userId: "u12", role: "regular" },
        { userId: "u13", role: "candidate" },
        { userId: "u14", role: "regular" },
      ],
    },
    {
      id: "t7",
      name: "Banpo Arc",
      homeCourt: "반포 선셋파크",
      region: "서초",
      mmr: 1248,
      wins: 9,
      losses: 12,
      accent: "#ffab4c",
      favorite: true,
      members: [
        { userId: "u15", role: "captain" },
        { userId: "u16", role: "regular" },
        { userId: "u17", role: "candidate" },
      ],
    },
    {
      id: "t8",
      name: "Noryangjin Press",
      homeCourt: "노량진 루프코트",
      region: "동작",
      mmr: 1198,
      wins: 8,
      losses: 14,
      accent: "#ff755f",
      favorite: true,
      members: [
        { userId: "u18", role: "captain" },
        { userId: "u19", role: "regular" },
        { userId: "u20", role: "guest" },
      ],
    },
    {
      id: "t9",
      name: "Yeonnam Rails",
      homeCourt: "연남 레일파크",
      region: "마포",
      mmr: 1226,
      wins: 12,
      losses: 16,
      accent: "#8ac7db",
      favorite: false,
      members: [
        { userId: "u21", role: "captain" },
        { userId: "u22", role: "regular" },
        { userId: "u23", role: "mercenary" },
      ],
    },
    {
      id: "t10",
      name: "Mullae Iron",
      homeCourt: "문래 팩토리코트",
      region: "영등포",
      mmr: 1302,
      wins: 15,
      losses: 13,
      accent: "#9aa4b2",
      favorite: false,
      members: [
        { userId: "u24", role: "captain" },
        { userId: "u25", role: "regular" },
        { userId: "u26", role: "candidate" },
      ],
    },
    {
      id: "t11",
      name: "Wangsimni Breakers",
      homeCourt: "왕십리 언더패스",
      region: "성동",
      mmr: 1176,
      wins: 7,
      losses: 15,
      accent: "#f05d5e",
      favorite: false,
      members: [
        { userId: "u27", role: "captain" },
        { userId: "u28", role: "regular" },
        { userId: "u29", role: "regular" },
      ],
    },
    {
      id: "t12",
      name: "Sinchon Blue",
      homeCourt: "신촌 블루짐",
      region: "서대문",
      mmr: 1210,
      wins: 10,
      losses: 14,
      accent: "#74a8ff",
      favorite: false,
      members: [
        { userId: "u30", role: "captain" },
        { userId: "u31", role: "regular" },
        { userId: "u32", role: "guest" },
      ],
    },
  ];
