// Transitional boundary for the legacy browser/demo repository.
// Server routes must import repository actions through this single adapter
// until the pure state reducers and remote loaders are physically separated.
export {
  acceptRecruitingInvitation,
  agreeMatch,
  approveMatch,
  approveTournamentTeam,
  cancelMatch,
  cancelRecruitingParticipation,
  checkInMatchPlayer,
  closeRecruitingPost,
  configureServerRatingAuthority,
  confirmMatchRefereeAbsence,
  confirmRecruitingMatch,
  createMatch,
  createRecruitingPost,
  createTournament,
  declineRecruitingInvitation,
  deleteSoloRecord,
  detachRecruitingPartyPlayer,
  disputeMatch,
  endMatch,
  forfeitTournamentMatch,
  interestRecruitingPost,
  inviteRecruitingPlayers,
  inviteRecruitingReferee,
  joinRecruitingSideParty,
  kickRecruitingApplicant,
  loadNormalizedDirectoryStateFromClient,
  loadNormalizedMatchDetailFromClient,
  loadNormalizedRemoteStateFromClient,
  removeMatchRoomPlayer,
  removeRecruitingPartyPlayer,
  requestMatchRefereeAbsence,
  resolveMatchDispute,
  sendRecruitingChat,
  setMatchRecordParticipants,
  setMatchRecordTeamRoster,
  setMatchRoomPlayerPlacement,
  setRecruitingApplicantPlacement,
  setRecruitingApplicantReserve,
  setRecruitingPartyPlayerPlacement,
  setRecruitingPartyPlayerReserve,
  setRecruitingRoomTeam,
  setRecruitingSlotPosition,
  setRecruitingTeamPartyRoster,
  startMatch,
  submitMatchResult,
  submitMatchThumbs,
  substituteMatchPlayer,
  toggleMatchStar,
  updateMatchRoomRules,
  updateRecruitingRoomRules,
  updateTournamentMatchSchedule,
  voidMatch,
} from "../../src/data/repository.js";
