create table if not exists public.match_clock_sessions (
  match_id text primary key references public.matches(id) on delete cascade,
  controller_id text,
  status text not null default 'pending',
  current_period smallint not null default 1,
  overtime_count smallint not null default 0,
  period_remaining_ms bigint not null default 0,
  shot_clock_seconds smallint not null default 0,
  shot_remaining_ms bigint not null default 0,
  active_elapsed_ms bigint not null default 0,
  last_resumed_at timestamptz,
  start_deadline_at timestamptz not null,
  clock_started_at timestamptz,
  clock_ended_at timestamptz,
  started_within_window boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint match_clock_sessions_status_check
    check (status in ('pending', 'running', 'paused', 'break', 'ended')),
  constraint match_clock_sessions_period_check check (current_period between 1 and 20),
  constraint match_clock_sessions_overtime_check check (overtime_count between 0 and 20),
  constraint match_clock_sessions_shot_clock_check check (shot_clock_seconds in (0, 30, 35, 60)),
  constraint match_clock_sessions_remaining_check
    check (period_remaining_ms >= 0 and shot_remaining_ms >= 0 and active_elapsed_ms >= 0)
);

create table if not exists public.match_clock_events (
  id bigint generated by default as identity primary key,
  match_id text not null references public.matches(id) on delete cascade,
  actor_id text,
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists match_clock_events_match_created_idx
  on public.match_clock_events (match_id, created_at, id);

alter table public.match_clock_sessions enable row level security;
alter table public.match_clock_events enable row level security;

revoke all on table public.match_clock_sessions from public, anon, authenticated;
revoke all on table public.match_clock_events from public, anon, authenticated;
grant select, insert, update, delete on table public.match_clock_sessions to service_role;
grant select, insert, update, delete on table public.match_clock_events to service_role;
grant usage, select on sequence public.match_clock_events_id_seq to service_role;

create or replace function public.rankball_match_clock_period_seconds(p_match_id text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select greatest(
    60,
    least(
      3600,
      case
        when coalesce(match_row.rules->>'periodMinutes', '') ~ '^[0-9]+$'
          then (match_row.rules->>'periodMinutes')::integer * 60
        when coalesce(match_row.rules->>'timeLimit', '') ~ '^[0-9]+$'
          then (match_row.rules->>'timeLimit')::integer * 60
        when match_row.mode = '5v5' then 600
        else 720
      end
    )
  )
  from public.matches match_row
  where match_row.id = nullif(btrim(p_match_id), '');
$$;

create or replace function public.rankball_match_clock_period_count(p_match_id text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select greatest(
    1,
    least(
      4,
      case
        when coalesce(match_row.rules->>'periodCount', '') ~ '^[0-9]+$'
          then (match_row.rules->>'periodCount')::integer
        when match_row.mode = '5v5' then 4
        else 1
      end
    )
  )
  from public.matches match_row
  where match_row.id = nullif(btrim(p_match_id), '');
$$;

create or replace function public.rankball_match_clock_overtime_seconds(p_match_id text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select greatest(
    60,
    least(
      1200,
      case
        when coalesce(match_row.rules->>'overtimeMinutes', '') ~ '^[0-9]+$'
          then (match_row.rules->>'overtimeMinutes')::integer * 60
        when match_row.mode = '5v5' then 300
        else 180
      end
    )
  )
  from public.matches match_row
  where match_row.id = nullif(btrim(p_match_id), '');
$$;

create or replace function public.rankball_match_clock_rating_factor(
  p_match_id text,
  p_mode text
)
returns numeric
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  session_row public.match_clock_sessions%rowtype;
  expected_ms bigint;
  fallback_factor numeric;
begin
  select * into session_row
  from public.match_clock_sessions
  where match_id = nullif(btrim(p_match_id), '');

  if session_row.match_id is null then
    return 1;
  end if;

  expected_ms := public.rankball_match_clock_period_seconds(session_row.match_id)::bigint
    * public.rankball_match_clock_period_count(session_row.match_id)::bigint
    * 1000;
  fallback_factor := case p_mode
    when '1v1' then 0.5
    when '2v2' then 0.65
    when '3v3' then 0.8
    when '5v5' then 0.9
    else 0.8
  end;

  if session_row.started_within_window
    and session_row.clock_started_at is not null
    and session_row.clock_ended_at is not null
    and session_row.active_elapsed_ms >= ceil(expected_ms * 0.7)::bigint
  then
    return 1;
  end if;

  return fallback_factor;
end;
$$;

create or replace function public.rankball_match_clock_create_session()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  initial_controller_id text;
  initial_period_ms bigint;
begin
  if new.started_at is null then
    return new;
  end if;
  if tg_op = 'UPDATE' and old.started_at is not null then
    return new;
  end if;

  select player.user_id into initial_controller_id
  from public.match_players player
  where player.match_id = new.id
  order by
    case when player.user_id = new.created_by then 0 else 1 end,
    case when player.side = 'teamA' then 0 else 1 end,
    player.slot_order,
    player.user_id
  limit 1;

  initial_period_ms := public.rankball_match_clock_period_seconds(new.id)::bigint * 1000;

  insert into public.match_clock_sessions (
    match_id,
    controller_id,
    status,
    current_period,
    overtime_count,
    period_remaining_ms,
    shot_clock_seconds,
    shot_remaining_ms,
    active_elapsed_ms,
    start_deadline_at,
    created_at,
    updated_at
  )
  values (
    new.id,
    initial_controller_id,
    'pending',
    1,
    0,
    initial_period_ms,
    0,
    0,
    0,
    new.started_at + interval '5 minutes',
    now(),
    now()
  )
  on conflict (match_id) do nothing;

  return new;
end;
$$;

drop trigger if exists rankball_match_clock_create_session_trigger on public.matches;
create trigger rankball_match_clock_create_session_trigger
after insert or update of started_at on public.matches
for each row
execute function public.rankball_match_clock_create_session();

create or replace function public.rankball_match_clock_action(
  p_actor_profile_id text,
  p_match_id text,
  p_action text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  safe_actor_id text := nullif(btrim(p_actor_profile_id), '');
  safe_match_id text := nullif(btrim(p_match_id), '');
  safe_action text := nullif(btrim(p_action), '');
  safe_payload jsonb := coalesce(p_payload, '{}'::jsonb);
  current_match public.matches%rowtype;
  session_row public.match_clock_sessions%rowtype;
  server_now timestamptz := clock_timestamp();
  is_manager boolean := false;
  is_active boolean := false;
  is_related boolean := false;
  elapsed_ms bigint := 0;
  applied_ms bigint := 0;
  expected_period_seconds integer;
  expected_period_count integer;
  overtime_seconds integer;
  minimum_active_ms bigint;
  target_controller_id text;
  next_shot_seconds integer;
  score_a integer := 0;
  score_b integer := 0;
  can_start_overtime boolean := false;
begin
  if safe_actor_id is null or safe_match_id is null or safe_action is null then
    raise exception 'missing_match_clock_action' using errcode = '22023';
  end if;

  if safe_action not in (
    'read',
    'configure',
    'start',
    'pause',
    'resume',
    'resetShot',
    'endPeriod',
    'startPeriod',
    'startOvertime',
    'transfer',
    'endClock'
  ) then
    raise exception 'invalid_match_clock_action' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtext('rankball:match-clock'), hashtext(safe_match_id));

  select * into current_match
  from public.matches
  where id = safe_match_id;

  if current_match.id is null then
    raise exception 'match_not_found' using errcode = 'P0002';
  end if;
  if current_match.started_at is null then
    raise exception 'match_not_started' using errcode = '55000';
  end if;

  is_manager := case
    when nullif(btrim(current_match.referee_id), '') is not null
      then current_match.referee_id = safe_actor_id
    else current_match.created_by = safe_actor_id
  end;
  select exists(
    select 1
    from public.match_players player
    where player.match_id = safe_match_id
      and player.user_id = safe_actor_id
  ) into is_active;
  is_related := is_manager
    or is_active
    or current_match.created_by = safe_actor_id
    or current_match.referee_id = safe_actor_id
    or current_match.former_referee_id = safe_actor_id
    or coalesce(current_match.reserve_players->'teamA', '[]'::jsonb) ? safe_actor_id
    or coalesce(current_match.reserve_players->'teamB', '[]'::jsonb) ? safe_actor_id
    or current_match.stat_recorders->>'teamA' = safe_actor_id
    or current_match.stat_recorders->>'teamB' = safe_actor_id;

  if not is_related then
    raise exception 'match_clock_forbidden' using errcode = '42501';
  end if;

  expected_period_seconds := public.rankball_match_clock_period_seconds(safe_match_id);
  expected_period_count := public.rankball_match_clock_period_count(safe_match_id);
  overtime_seconds := public.rankball_match_clock_overtime_seconds(safe_match_id);
  minimum_active_ms := ceil(expected_period_seconds::numeric * expected_period_count * 1000 * 0.7)::bigint;

  insert into public.match_clock_sessions (
    match_id,
    controller_id,
    status,
    current_period,
    overtime_count,
    period_remaining_ms,
    shot_clock_seconds,
    shot_remaining_ms,
    active_elapsed_ms,
    start_deadline_at,
    created_at,
    updated_at
  )
  select
    current_match.id,
    (
      select player.user_id
      from public.match_players player
      where player.match_id = current_match.id
      order by
        case when player.user_id = current_match.created_by then 0 else 1 end,
        case when player.side = 'teamA' then 0 else 1 end,
        player.slot_order,
        player.user_id
      limit 1
    ),
    'pending',
    1,
    0,
    expected_period_seconds::bigint * 1000,
    0,
    0,
    0,
    current_match.started_at + interval '5 minutes',
    server_now,
    server_now
  where not exists (
    select 1 from public.match_clock_sessions existing where existing.match_id = current_match.id
  );

  if safe_action = 'read' then
    select * into session_row
    from public.match_clock_sessions
    where match_id = safe_match_id;
  else
    select * into session_row
    from public.match_clock_sessions
    where match_id = safe_match_id
    for update;
  end if;

  if session_row.status = 'running' and session_row.last_resumed_at is not null then
    elapsed_ms := greatest(
      0,
      floor(extract(epoch from (server_now - session_row.last_resumed_at)) * 1000)::bigint
    );
    applied_ms := least(elapsed_ms, session_row.period_remaining_ms);
    session_row.period_remaining_ms := greatest(0, session_row.period_remaining_ms - applied_ms);
    session_row.active_elapsed_ms := session_row.active_elapsed_ms + applied_ms;
    if session_row.shot_clock_seconds > 0 then
      session_row.shot_remaining_ms := greatest(0, session_row.shot_remaining_ms - applied_ms);
    end if;
    if session_row.period_remaining_ms = 0 then
      session_row.status := 'paused';
      session_row.last_resumed_at := null;
    else
      session_row.last_resumed_at := server_now;
    end if;
  end if;

  if safe_action = 'read' then
    null;
  elsif safe_action = 'configure' then
    if not is_manager or session_row.clock_started_at is not null then
      raise exception 'match_clock_configure_forbidden' using errcode = '42501';
    end if;
    target_controller_id := nullif(btrim(safe_payload->>'controllerId'), '');
    if target_controller_id is null or not exists (
      select 1 from public.match_players player
      where player.match_id = safe_match_id and player.user_id = target_controller_id
    ) then
      raise exception 'match_clock_controller_must_be_active' using errcode = '22023';
    end if;
    next_shot_seconds := case
      when coalesce(safe_payload->>'shotClockSeconds', '') ~ '^[0-9]+$'
        then (safe_payload->>'shotClockSeconds')::integer
      else 0
    end;
    if next_shot_seconds not in (0, 30, 35, 60) then
      raise exception 'invalid_shot_clock_seconds' using errcode = '22023';
    end if;
    session_row.controller_id := target_controller_id;
    session_row.shot_clock_seconds := next_shot_seconds;
    session_row.shot_remaining_ms := next_shot_seconds::bigint * 1000;
  elsif safe_action = 'start' then
    if session_row.controller_id <> safe_actor_id or session_row.clock_started_at is not null then
      raise exception 'match_clock_start_forbidden' using errcode = '42501';
    end if;
    session_row.status := 'running';
    session_row.clock_started_at := server_now;
    session_row.started_within_window := server_now <= session_row.start_deadline_at;
    session_row.last_resumed_at := server_now;
    session_row.period_remaining_ms := expected_period_seconds::bigint * 1000;
    session_row.shot_remaining_ms := session_row.shot_clock_seconds::bigint * 1000;
  elsif safe_action = 'pause' then
    if session_row.controller_id <> safe_actor_id or session_row.status <> 'running' then
      raise exception 'match_clock_pause_forbidden' using errcode = '42501';
    end if;
    session_row.status := 'paused';
    session_row.last_resumed_at := null;
  elsif safe_action = 'resume' then
    if session_row.controller_id <> safe_actor_id
      or session_row.status <> 'paused'
      or session_row.period_remaining_ms <= 0
    then
      raise exception 'match_clock_resume_forbidden' using errcode = '42501';
    end if;
    session_row.status := 'running';
    session_row.last_resumed_at := server_now;
  elsif safe_action = 'resetShot' then
    if session_row.controller_id <> safe_actor_id or session_row.shot_clock_seconds = 0 then
      raise exception 'match_clock_shot_forbidden' using errcode = '42501';
    end if;
    session_row.shot_remaining_ms := session_row.shot_clock_seconds::bigint * 1000;
  elsif safe_action = 'endPeriod' then
    if session_row.controller_id <> safe_actor_id
      or session_row.status not in ('running', 'paused')
    then
      raise exception 'match_clock_period_end_forbidden' using errcode = '42501';
    end if;
    session_row.status := 'break';
    session_row.period_remaining_ms := 0;
    session_row.shot_remaining_ms := session_row.shot_clock_seconds::bigint * 1000;
    session_row.last_resumed_at := null;
  elsif safe_action = 'startPeriod' then
    if session_row.controller_id <> safe_actor_id
      or session_row.status <> 'break'
      or session_row.current_period >= expected_period_count
      or session_row.overtime_count > 0
    then
      raise exception 'match_clock_period_start_forbidden' using errcode = '42501';
    end if;
    session_row.current_period := session_row.current_period + 1;
    session_row.period_remaining_ms := expected_period_seconds::bigint * 1000;
    session_row.shot_remaining_ms := session_row.shot_clock_seconds::bigint * 1000;
    session_row.status := 'running';
    session_row.last_resumed_at := server_now;
  elsif safe_action = 'startOvertime' then
    if session_row.controller_id <> safe_actor_id
      or session_row.status <> 'break'
      or session_row.current_period < expected_period_count
    then
      raise exception 'match_clock_overtime_forbidden' using errcode = '42501';
    end if;
    select coalesce(result.score_a, current_match.score_a, 0),
      coalesce(result.score_b, current_match.score_b, 0)
    into score_a, score_b
    from public.matches match_row
    left join public.match_results result on result.match_id = match_row.id
    where match_row.id = safe_match_id;
    can_start_overtime := score_a = score_b;
    if not can_start_overtime then
      raise exception 'match_clock_overtime_requires_tie' using errcode = '22023';
    end if;
    session_row.overtime_count := session_row.overtime_count + 1;
    session_row.period_remaining_ms := overtime_seconds::bigint * 1000;
    session_row.shot_remaining_ms := session_row.shot_clock_seconds::bigint * 1000;
    session_row.status := 'running';
    session_row.last_resumed_at := server_now;
  elsif safe_action = 'transfer' then
    if session_row.controller_id <> safe_actor_id and not is_manager then
      raise exception 'match_clock_transfer_forbidden' using errcode = '42501';
    end if;
    target_controller_id := nullif(btrim(safe_payload->>'controllerId'), '');
    if target_controller_id is null or not exists (
      select 1 from public.match_players player
      where player.match_id = safe_match_id and player.user_id = target_controller_id
    ) then
      raise exception 'match_clock_controller_must_be_active' using errcode = '22023';
    end if;
    session_row.controller_id := target_controller_id;
  elsif safe_action = 'endClock' then
    if session_row.controller_id <> safe_actor_id or session_row.clock_started_at is null then
      raise exception 'match_clock_end_forbidden' using errcode = '42501';
    end if;
    session_row.status := 'ended';
    session_row.clock_ended_at := server_now;
    session_row.last_resumed_at := null;
  end if;

  if safe_action <> 'read' then
    update public.match_clock_sessions
    set
      controller_id = session_row.controller_id,
      status = session_row.status,
      current_period = session_row.current_period,
      overtime_count = session_row.overtime_count,
      period_remaining_ms = session_row.period_remaining_ms,
      shot_clock_seconds = session_row.shot_clock_seconds,
      shot_remaining_ms = session_row.shot_remaining_ms,
      active_elapsed_ms = session_row.active_elapsed_ms,
      last_resumed_at = session_row.last_resumed_at,
      clock_started_at = session_row.clock_started_at,
      clock_ended_at = session_row.clock_ended_at,
      started_within_window = session_row.started_within_window,
      updated_at = server_now
    where match_id = safe_match_id
    returning * into session_row;

    insert into public.match_clock_events (match_id, actor_id, action, payload, created_at)
    values (
      safe_match_id,
      safe_actor_id,
      safe_action,
      safe_payload || jsonb_build_object(
        'status', session_row.status,
        'currentPeriod', session_row.current_period,
        'overtimeCount', session_row.overtime_count,
        'activeElapsedMs', session_row.active_elapsed_ms
      ),
      server_now
    );
  end if;

  return jsonb_build_object(
    'matchId', session_row.match_id,
    'controllerId', session_row.controller_id,
    'status', session_row.status,
    'currentPeriod', session_row.current_period,
    'overtimeCount', session_row.overtime_count,
    'periodRemainingMs', session_row.period_remaining_ms,
    'shotClockSeconds', session_row.shot_clock_seconds,
    'shotRemainingMs', session_row.shot_remaining_ms,
    'activeElapsedMs', session_row.active_elapsed_ms,
    'lastResumedAt', session_row.last_resumed_at,
    'startDeadlineAt', session_row.start_deadline_at,
    'clockStartedAt', session_row.clock_started_at,
    'clockEndedAt', session_row.clock_ended_at,
    'startedWithinWindow', session_row.started_within_window,
    'expectedPeriodSeconds', expected_period_seconds,
    'expectedPeriodCount', expected_period_count,
    'overtimeSeconds', overtime_seconds,
    'minimumActiveMs', minimum_active_ms,
    'clockUsed', session_row.started_within_window
      and session_row.clock_started_at is not null
      and session_row.clock_ended_at is not null
      and session_row.active_elapsed_ms >= minimum_active_ms,
    'canManage', is_manager,
    'canControl', session_row.controller_id = safe_actor_id,
    'serverNow', server_now
  );
end;
$$;

revoke all on function public.rankball_match_clock_period_seconds(text) from public, anon, authenticated;
revoke all on function public.rankball_match_clock_period_count(text) from public, anon, authenticated;
revoke all on function public.rankball_match_clock_overtime_seconds(text) from public, anon, authenticated;
revoke all on function public.rankball_match_clock_rating_factor(text, text) from public, anon, authenticated;
revoke all on function public.rankball_match_clock_action(text, text, text, jsonb) from public, anon, authenticated;
grant execute on function public.rankball_match_clock_period_seconds(text) to service_role;
grant execute on function public.rankball_match_clock_period_count(text) to service_role;
grant execute on function public.rankball_match_clock_overtime_seconds(text) to service_role;
grant execute on function public.rankball_match_clock_rating_factor(text, text) to service_role;
grant execute on function public.rankball_match_clock_action(text, text, text, jsonb) to service_role;

do $migration$
declare
  function_definition text;
  old_text text := $old$    * greatest(0.2, least(1.15, coalesce((current_match.rules->>'ratingScale')::numeric, 1)))$old$;
  new_text text := $new$    * greatest(0.2, least(1.15, coalesce((current_match.rules->>'ratingScale')::numeric, 1)))
    * public.rankball_match_clock_rating_factor(safe_match_id, current_match.mode)$new$;
begin
  function_definition := pg_get_functiondef(
    'public.rankball_match_finalize_locked_concurrency_inner(text,text,text)'::regprocedure
  );
  if position('public.rankball_match_clock_rating_factor(safe_match_id, current_match.mode)' in function_definition) = 0 then
    if position(old_text in function_definition) = 0 then
      raise exception 'match_clock_finalize_quality_shape_changed' using errcode = '55000';
    end if;
    function_definition := replace(function_definition, old_text, new_text);
    execute function_definition;
  end if;
end;
$migration$;

select pg_notify('pgrst', 'reload schema');
