alter table public.instagram_receipt_bot_requests
  add column if not exists principal_hash text,
  add column if not exists profile_id text references public.profiles(id) on delete set null,
  add column if not exists request_kind text;

update public.instagram_receipt_bot_requests
set principal_hash = sender_hash
where principal_hash is null;

update public.instagram_receipt_bot_requests
set request_kind = 'receipt'
where request_kind is null;

alter table public.instagram_receipt_bot_requests
  alter column principal_hash set not null,
  alter column request_kind set not null,
  alter column request_kind set default 'receipt';

alter table public.instagram_receipt_bot_requests
  drop constraint if exists instagram_receipt_bot_requests_principal_hash_check;
alter table public.instagram_receipt_bot_requests
  add constraint instagram_receipt_bot_requests_principal_hash_check check (char_length(principal_hash) = 64);
alter table public.instagram_receipt_bot_requests
  drop constraint if exists instagram_receipt_bot_requests_request_kind_check;
alter table public.instagram_receipt_bot_requests
  add constraint instagram_receipt_bot_requests_request_kind_check check (request_kind in ('receipt', 'command'));
alter table public.instagram_receipt_bot_requests
  drop constraint if exists instagram_receipt_bot_requests_outcome_check;
alter table public.instagram_receipt_bot_requests
  add constraint instagram_receipt_bot_requests_outcome_check
  check (outcome in ('help', 'image_sent', 'link_sent', 'history_sent', 'link_required', 'failed'));

create index if not exists instagram_receipt_bot_requests_principal_created_idx
  on public.instagram_receipt_bot_requests (principal_hash, created_at desc);

create table if not exists public.instagram_receipt_bot_accounts (
  sender_hash text primary key check (char_length(sender_hash) = 64),
  profile_id text not null unique references public.profiles(id) on delete cascade,
  linked_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.instagram_receipt_bot_link_codes (
  code_hash text primary key check (char_length(code_hash) = 64),
  sender_hash text not null check (char_length(sender_hash) = 64),
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists instagram_receipt_bot_link_codes_sender_idx
  on public.instagram_receipt_bot_link_codes (sender_hash, created_at desc);
create index if not exists instagram_receipt_bot_link_codes_expires_idx
  on public.instagram_receipt_bot_link_codes (expires_at);

create table if not exists public.instagram_receipt_bot_history (
  id bigint generated by default as identity primary key,
  event_hash text not null unique check (char_length(event_hash) = 64),
  sender_hash text not null check (char_length(sender_hash) = 64),
  profile_id text references public.profiles(id) on delete cascade,
  receipt_summary jsonb not null check (jsonb_typeof(receipt_summary) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists instagram_receipt_bot_history_profile_created_idx
  on public.instagram_receipt_bot_history (profile_id, created_at desc);
create index if not exists instagram_receipt_bot_history_sender_created_idx
  on public.instagram_receipt_bot_history (sender_hash, created_at desc);

create index if not exists instagram_receipt_bot_history_created_idx
  on public.instagram_receipt_bot_history (created_at);

alter table public.instagram_receipt_bot_accounts enable row level security;
alter table public.instagram_receipt_bot_link_codes enable row level security;
alter table public.instagram_receipt_bot_history enable row level security;

revoke all on table public.instagram_receipt_bot_accounts from public, anon, authenticated;
revoke all on table public.instagram_receipt_bot_link_codes from public, anon, authenticated;
revoke all on table public.instagram_receipt_bot_history from public, anon, authenticated;
grant select, insert, update, delete on table public.instagram_receipt_bot_accounts to service_role;
grant select, insert, update, delete on table public.instagram_receipt_bot_link_codes to service_role;
grant select, insert, update, delete on table public.instagram_receipt_bot_history to service_role;
grant usage, select on sequence public.instagram_receipt_bot_history_id_seq to service_role;

create or replace function public.claim_instagram_receipt_bot_request_v2(
  p_event_hash text,
  p_sender_hash text,
  p_principal_hash text,
  p_profile_id text,
  p_content_hash text,
  p_request_kind text,
  p_cooldown_seconds integer,
  p_hour_limit integer,
  p_day_limit integer,
  p_global_hour_limit integer,
  p_content_dedupe_seconds integer
) returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now timestamptz := now();
  v_decision text;
begin
  if char_length(p_event_hash) <> 64 or char_length(p_sender_hash) <> 64
     or char_length(p_principal_hash) <> 64 or char_length(p_content_hash) <> 64
     or p_request_kind not in ('receipt', 'command')
     or p_cooldown_seconds not between 1 and 86400
     or p_hour_limit not between 1 and 1000
     or p_day_limit not between 1 and 10000
     or p_global_hour_limit not between 1 and 100000
     or p_content_dedupe_seconds not between 1 and 86400 then
    raise exception 'invalid_instagram_receipt_bot_limit';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_event_hash, 0));
  perform pg_advisory_xact_lock(hashtextextended(p_principal_hash, 1));

  if exists (select 1 from public.instagram_receipt_bot_requests where event_hash = p_event_hash) then
    return 'duplicate_event';
  end if;

  if exists (
    select 1 from public.instagram_receipt_bot_requests
    where sender_hash = p_sender_hash and content_hash = p_content_hash and decision = 'accepted'
      and created_at >= v_now - make_interval(secs => p_content_dedupe_seconds)
  ) then
    v_decision := 'duplicate_content';
  elsif exists (
    select 1 from public.instagram_receipt_bot_requests
    where principal_hash = p_principal_hash and decision = 'accepted'
      and created_at >= v_now - make_interval(secs => p_cooldown_seconds)
  ) then
    v_decision := 'cooldown';
  elsif (select count(*) from public.instagram_receipt_bot_requests
         where principal_hash = p_principal_hash and decision = 'accepted'
           and created_at >= v_now - interval '1 hour') >= p_hour_limit then
    v_decision := 'hourly_limit';
  elsif p_request_kind = 'receipt' and (
    select count(*) from public.instagram_receipt_bot_requests
    where principal_hash = p_principal_hash and request_kind = 'receipt' and decision = 'accepted'
      and created_at >= v_now - interval '1 day'
  ) >= p_day_limit then
    v_decision := 'daily_limit';
  else
    perform pg_advisory_xact_lock(hashtextextended('instagram_receipt_bot_global', 2));
    if (select count(*) from public.instagram_receipt_bot_requests
        where decision = 'accepted' and created_at >= v_now - interval '1 hour') >= p_global_hour_limit then
      v_decision := 'global_limit';
    else
      v_decision := 'accepted';
    end if;
  end if;

  insert into public.instagram_receipt_bot_requests (
    event_hash, sender_hash, principal_hash, profile_id, content_hash, request_kind, decision
  ) values (
    p_event_hash, p_sender_hash, p_principal_hash, p_profile_id, p_content_hash, p_request_kind, v_decision
  );
  return v_decision;
end;
$$;

create or replace function public.consume_instagram_receipt_bot_link(
  p_code_hash text,
  p_profile_id text
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sender_hash text;
begin
  if char_length(p_code_hash) <> 64 or coalesce(p_profile_id, '') = '' then
    return false;
  end if;

  select sender_hash into v_sender_hash
  from public.instagram_receipt_bot_link_codes
  where code_hash = p_code_hash and expires_at > now()
  for update;

  if v_sender_hash is null then
    return false;
  end if;

  delete from public.instagram_receipt_bot_accounts
  where sender_hash = v_sender_hash or profile_id = p_profile_id;

  insert into public.instagram_receipt_bot_accounts (sender_hash, profile_id)
  values (v_sender_hash, p_profile_id);

  update public.instagram_receipt_bot_history
  set profile_id = p_profile_id
  where sender_hash = v_sender_hash;

  delete from public.instagram_receipt_bot_link_codes
  where code_hash = p_code_hash;

  return true;
end;
$$;

create or replace function public.cleanup_instagram_receipt_bot_data()
returns void
language sql
security definer
set search_path = ''
as $$
  delete from public.instagram_receipt_bot_render_jobs where expires_at <= now();
  delete from public.instagram_receipt_bot_link_codes where expires_at <= now();
  delete from public.instagram_receipt_bot_requests where created_at < now() - interval '7 days';
  delete from public.instagram_receipt_bot_history
  where (profile_id is null and created_at < now() - interval '30 days')
     or created_at < now() - interval '1 year';
$$;

revoke all on function public.claim_instagram_receipt_bot_request_v2(text, text, text, text, text, text, integer, integer, integer, integer, integer) from public, anon, authenticated;
revoke all on function public.consume_instagram_receipt_bot_link(text, text) from public, anon, authenticated;
revoke all on function public.cleanup_instagram_receipt_bot_data() from public, anon, authenticated;
grant execute on function public.claim_instagram_receipt_bot_request_v2(text, text, text, text, text, text, integer, integer, integer, integer, integer) to service_role;
grant execute on function public.consume_instagram_receipt_bot_link(text, text) to service_role;
grant execute on function public.cleanup_instagram_receipt_bot_data() to service_role;
