import { getSupabaseAdminClient } from "../_supabaseAdmin.js";
import {
  allowSystemReadRequest,
  assertSystemSecretAccess,
  readSystemRequestBody,
  sendJson,
} from "./_systemRequest.js";

export const REQUIRED_COLUMNS = {
  profiles: [
    "id",
    "auth_user_id",
    "test_login_id",
    "hashtag",
    "onboarding_complete",
    "discord_user_id",
    "avatar_key",
    "avatar_source",
    "avatar_icon_key",
    "avatar_uploaded_at",
    "avatar_upload_count",
    "avatar_background_enabled",
    "avatar_border_enabled",
    "avatar_border_color",
    "discord_avatar_url",
    "placement_match_count",
    "placement_evidence_weight",
    "placement_weighted_sum",
    "placement_completed_at",
  ],
  public_profiles: [
    "id",
    "name",
    "hashtag",
    "trust_score",
    "updated_at",
    "avatar_key",
    "avatar_source",
    "avatar_icon_key",
    "avatar_background_enabled",
    "avatar_border_enabled",
    "avatar_border_color",
    "discord_avatar_url",
    "placement_match_count",
  ],
  teams: [
    "id",
    "name",
    "home_court",
    "region",
    "emblem_key",
    "emblem_previous_key",
    "emblem_source",
    "emblem_updated_at",
    "emblem_uploaded_at",
    "emblem_upload_count",
    "emblem_color",
    "emblem_border_enabled",
    "emblem_border_color",
    "emblem_text_mode",
    "emblem_abbreviation",
    "emblem_font",
    "emblem_violation_count",
    "emblem_upload_blocked_until",
    "emblem_moderated_at",
    "emblem_moderation_reason",
    "deleted_at",
    "roster_mmr",
    "performance_adjustment",
  ],
  team_members: [
    "team_id",
    "user_id",
    "role",
  ],
  recruiting_posts: [
    "id",
    "visibility",
    "player_id",
    "mode",
    "room_state",
    "host_join_mode",
    "host_ready",
    "side_capacity",
    "bench_capacity",
    "dispute_minutes",
    "status",
  ],
  recruiting_applications: [
    "post_id",
    "player_id",
    "kind",
    "side",
    "status",
    "player_ids",
  ],
  room_remake_events: [
    "id",
    "owner_id",
    "root_source_type",
    "root_source_id",
    "source_post_id",
    "source_match_id",
    "new_post_id",
    "sequence",
    "warning_level",
    "created_at",
  ],
  matches: [
    "id",
    "title",
    "mode",
    "court_name",
    "visibility",
    "status",
    "ranked",
    "scheduled_date",
    "scheduled_time",
    "team_a_id",
    "team_b_id",
    "score_a",
    "score_b",
    "rules",
    "dispute_minutes",
    "created_by",
    "agreed_at",
    "started_at",
    "ended_at",
    "confirmed_at",
    "cancelled_at",
    "voided_at",
    "updated_at",
    "dual_score_recorder_side",
  ],
  match_players: [
    "match_id",
    "user_id",
    "side",
    "slot_order",
    "position",
  ],
  match_attendance_entries: [
    "match_id",
    "player_id",
    "side",
    "original_role",
    "status",
    "method",
    "checked_in_at",
    "updated_at",
  ],
  match_substitution_events: [
    "id",
    "match_id",
    "side",
    "active_out_player_id",
    "active_in_player_id",
    "reason",
    "confirmed_by",
    "clock_active_elapsed_ms",
    "minimum_meaningful_seconds",
    "created_at",
  ],
  match_play_intervals: [
    "id",
    "match_id",
    "player_id",
    "side",
    "started_at",
    "started_active_elapsed_ms",
    "ended_at",
    "ended_active_elapsed_ms",
  ],
  match_score_events: [
    "id",
    "match_id",
    "side",
    "actor_profile_id",
    "event_type",
    "requested_delta",
    "score_before",
    "score_after",
    "score_revision",
    "authority_scope",
    "created_at",
  ],
  match_recorder_takeover_requests: [
    "id",
    "match_id",
    "side",
    "requested_by",
    "expected_recorder_id",
    "status",
    "created_at",
    "resolved_at",
    "resolved_by",
  ],
  profile_icon_unlocks: [
    "profile_id",
    "icon_key",
    "unlocked_at",
    "progress_snapshot",
  ],
  match_player_competitive_snapshots: [
    "match_id",
    "profile_id",
    "side",
    "age_group",
    "mode_mmr",
    "integrated_mmr",
    "mmr_eligible",
    "team_id",
    "team_role",
    "snapshot_source",
    "snapshotted_at",
  ],
  match_record_archives: [
    "match_id",
    "archive_version",
    "record_date",
    "occurred_at",
    "payload",
    "is_active",
    "updated_at",
  ],
  match_record_participants: [
    "match_id",
    "profile_id",
    "record_date",
    "side",
    "team_name",
    "opponent_team_name",
    "score_for",
    "score_against",
    "outcome",
    "stats",
    "record_type",
    "visibility",
    "owner_profile_id",
  ],
  match_record_teams: [
    "match_id",
    "team_id",
    "record_date",
    "side",
    "team_name",
    "opponent_team_name",
    "score_for",
    "score_against",
    "outcome",
    "visibility",
    "reader_ids",
  ],
  match_record_refresh_queue: [
    "match_id",
    "queued_at",
  ],
  user_room_feed: [
    "profile_id",
    "entity_type",
    "entity_id",
    "relation",
    "feed_scope",
    "region_key",
    "status",
    "timing_type",
    "scheduled_date",
    "card_json",
    "sort_at",
    "is_active",
  ],
  room_feed_cards: [
    "entity_type",
    "entity_id",
    "card_json",
    "updated_at",
  ],
  match_results: [
    "match_id",
    "score_a",
    "score_b",
    "submitted_by",
    "result_revision",
    "stat_submissions",
    "score_revision_a",
    "score_revision_b",
    "score_submissions",
  ],
  player_match_stats: [
    "match_id",
    "user_id",
    "points",
    "rebounds",
    "assists",
    "steals",
    "blocks",
    "turnovers",
    "fouls",
  ],
  profile_personal_record_summaries: [
    "profile_id", "record_count", "win_count", "loss_count", "draw_count", "stat_count",
    "points", "rebounds", "assists", "steals", "blocks", "fouls",
    "public_record_count", "public_win_count", "public_loss_count", "public_draw_count", "public_stat_count",
    "public_points", "public_rebounds", "public_assists", "public_steals", "public_blocks", "public_fouls",
    "last_record_id", "last_record_at", "updated_at",
  ],
  profile_match_summaries: [
    "profile_id",
    "match_count",
    "win_count",
    "stat_match_count",
    "loss_count",
    "draw_count",
    "points",
    "rebounds",
    "assists",
    "steals",
    "blocks",
    "fouls",
    "last_match_id",
    "last_match_at",
    "updated_at",
  ],
  match_agreements: [
    "match_id",
    "user_id",
    "side",
  ],
  match_approvals: [
    "match_id",
    "user_id",
    "side",
  ],
  match_disputes: [
    "match_id",
    "user_id",
    "reason",
    "request_payload",
    "status",
  ],
  favorites: [
    "user_id",
    "target_type",
    "target_id",
  ],
  approved_courts: [
    "id",
    "name",
    "status",
    "region_key",
    "updated_at",
  ],
  notifications: [
    "id",
    "user_id",
    "target_user_id",
    "match_id",
    "recruiting_post_id",
    "due_at",
    "payload",
  ],
  discord_notification_deliveries: [
    "id",
    "notification_id",
    "target_user_id",
    "discord_user_id",
    "event",
    "status",
    "payload",
    "queued_at",
    "send_at",
    "sent_at",
    "attempt_count",
  ],
  room_chat_messages: [
    "id",
    "room_type",
    "room_id",
    "user_id",
    "body",
    "message_seq",
    "source",
    "external_message_id",
    "external_channel_id",
    "external_thread_id",
    "metadata",
  ],
  room_discord_links: [
    "id",
    "room_type",
    "room_id",
    "discord_channel_id",
    "discord_thread_id",
    "enabled",
  ],
  rating_policy: [
    "id",
    "version",
    "policy",
    "reason",
    "updated_by",
    "updated_at",
  ],
};
